Translate file licensce.po
pygreece/python-docs-gr pull request #138
Opened 2024-04-21 14:36 UTC by skpanagiotis

## Ποιο issue κλείνει το συγκεκριμένο PR;

Closes #16 

## Περιγραφή του PR

Μετάφραση του αρχείου license.po.

2024-04-22 09:15 UTC, thepetk requested changes
@skpanagiotis πάρα πολύ καλή δουλειά και ένα από τα πιο δύσκολα αρχεία! Έχω αφήσει κάποια suggestions αν θέλεις ρίξε μια ματιά.

Δύο κύρια σχόλια έχω γενικά και θα ήθελα την γνώμη σου σχετικά με την μετάφραση ή μη του included (βλ. σχόλιο παρακάτω) και του test suite.

2024-04-22 09:15 UTC, thepetk commented on license.po
> +"του αλγορίθμου τού Dan Bernstein SipHash24. Αυτό περιέχει την παρακάτω σημείωση::"
```suggestion
"του αλγορίθμου τού Dan Bernstein, SipHash24. Αυτό περιέχει την παρακάτω σημείωση::"
```

2024-04-22 09:15 UTC, thepetk commented on license.po
> +"C για μετατροπή του C doubles προς και από strings, προέρχεται από το ομώνυμο "
```suggestion
"C για μετατροπή των C doubles προς και από strings, προέρχεται από το ομώνυμο "
```

2024-04-22 09:15 UTC, thepetk commented on license.po
> +"αρχείο του David M. Gay, προς το παρόν διαθέσιμο από https://web.archive. "
```suggestion
"αρχείο του David M. Gay, προς το παρόν διαθέσιμο από https://web.archive."
```

2024-04-22 09:15 UTC, thepetk commented on license.po
> +"OpenSSL, επομένω συμπεριλαμβάνουμε ένα αντίγραφο της άδεια OpenSSL εδώ. Για την "
```suggestion
"OpenSSL, επομένως συμπεριλαμβάνουμε ένα αντίγραφο της άδειας OpenSSL εδώ. Για την "
```

2024-04-22 09:15 UTC, thepetk commented on license.po
> +"έκδοση OpenSSL 3.0 και για νεότερες εκδόσης που προέρχονται από αυτή, ισχύει "
```suggestion
"έκδοση OpenSSL 3.0 και για νεότερες εκδόσεις που προέρχονται από αυτή, ισχύει "
```

2024-04-22 09:15 UTC, thepetk commented on license.po
> +"ένα συμπεριλαμβανόμενο αντίγραφο των πηγών expat, εκτός εάν η έκδοση έχει την ρύθμιση "
Εδώ δεν είμαι σίγουρος αν πρέπει να μεταφράσουμε το included ή όχι.

@lysnikolaou

2024-04-22 09:15 UTC, thepetk commented on license.po
> +":mod:`ctypes` δημιουργείται χρησιμοποιώντας ένα συμπεριλαμβανόμενο αντίγραφο των "
βλ. παραπάνω σχόλιο για το included

2024-04-22 09:15 UTC, thepetk commented on license.po
> +"είναι πολύ παγια για να χρησιμοποηθεί για την κατασκευή. "
```suggestion
"είναι πολύ παλιά για να χρησιμοποηθεί για την κατασκευή. "
```

2024-04-22 09:15 UTC, thepetk commented on license.po
> +msgstr "W3C C14N σουίτα δοκιμής"
Και εδώ δεν ξέρω αν θα μετέφραζα το test suite.

@lysnikolaou

2024-04-22 09:15 UTC, thepetk commented on license.po
> +"Η μονάδα audioop χρησιμοποιεί ως βάση κώδικα του αρχείου g771.c του έργου Sox. "
```suggestion
"Το module audioop χρησιμοποιεί ως βάση κώδικα του αρχείου g771.c του έργου Sox. "
```

2024-04-22 09:15 UTC, thepetk commented on license.po
> +"Ο ΠΗΓΑΙΟΣ ΚΩΔΙΚΑ ΤΟΥ SUN ΠΑΡΕΧΕΤΑΙ ΟΠΩΣ ΕΧΕΙ ΧΩΡΙΣ ΚΑΝΕΝΟΣ ΕΙΔΟΥ ΕΓΓΥΣΕΙΣ "
```suggestion
"Ο ΠΗΓΑΙΟΣ ΚΩΔΙΚΑΣ ΤΟΥ SUN ΠΑΡΕΧΕΤΑΙ ΟΠΩΣ ΕΧΕΙ ΧΩΡΙΣ ΚΑΝΕΝΟΣ ΕΙΔΟΥΣ ΕΓΓΥΗΣΕΙΣ "
```

2024-04-22 09:15 UTC, thepetk commented on license.po
> +"ΣΥΜΠΕΡΙΛΑΜΒΑΝΟΜΕΝΩΝ ΕΓΓΥΣΕΩΝ ΣΧΕΔΙΑΣΜΟΥ, ΕΜΠΟΡΕΥΣΙΜΟΤΗΤΑΣ ΚΑΙ ΚΑΤΑΛΛΗΛΟΤΗΤΑΣ "
```suggestion
"ΣΥΜΠΕΡΙΛΑΜΒΑΝΟΜΕΝΩΝ ΕΓΓΥΗΣΕΩΝ ΣΧΕΔΙΑΣΜΟΥ, ΕΜΠΟΡΕΥΣΙΜΟΤΗΤΑΣ ΚΑΙ ΚΑΤΑΛΛΗΛΟΤΗΤΑΣ "
```

2024-04-22 09:19 UTC, thepetk commented
@skpanagiotis συγκεκριμένο PR επιλύει και το issue https://github.com/pygreece/python-docs-gr/issues/15. Αν θέλεις κάνε ένα comment και εκεί για να στο κάνω assign. Το μόνο που μένει στο συγκεκριμένο PR είναι να αφαιρεθεί τελείως το [LICENSE](https://github.com/pygreece/python-docs-gr/blob/main/LICENSE)

2024-04-22 10:29 UTC, skpanagiotis commented
@thepetk  σε Ευχαριστώ πολύ για τα σχόλια, θα τα διορθώσω και θα είμαι λίγο πιο προσεκτικός σε απροσεξίες και μικρολαθάκια. Όσο για τις λέξεις **test suite** και **included**, παρατήρησα ότι η μετάφραση στα ισπανικά δεν αφήνει τις λέξεις ίδιες αλλά τις μεταφράζει. Για αυτό έκανα την μετάφραση.

2024-04-22 10:33 UTC, thepetk commented
> @thepetk σε Ευχαριστώ πολύ για τα σχόλια, θα τα διορθώσω και θα είμαι λίγο πιο προσεκτικός σε απροσεξίες και μικρολαθάκια. Όσο για τις λέξεις **test suite** και **included**, παρατήρησα ότι η μετάφραση στα ισπανικά δεν αφήνει τις λέξεις ίδιες αλλά τις μεταφράζει. Για αυτό έκανα την μετάφραση.

Καλά εννοείται πως όλοι κάνουμε μικρολαθάκια! Νομίζω είναι καλό point για την ισπανική μετάφραση άρα ας το κρατήσουμε έτσι. Νομίζω θα πρέπει να τρέξεις και το `powrap` για το license.po (το test workflow αποτυγχάνει για αυτό).

2024-04-22 21:45 UTC, skpanagiotis commented
Έκανα τις αλλαγές που μου υπέδειξες όπως επίσης διέγραψα το LICENSE σύμφωνα με το issue #15.

2024-04-23 11:00 UTC, thepetk approved these changes
lgtm

2024-04-23 11:13 UTC, thepetk requested changes
Άφησα ένα πολύ μικρό suggestion. Επίσης μπορείς να βάλεις τα στοιχεία σου εδώ (αν θελεις):

https://github.com/pygreece/python-docs-gr/blob/fe868badaf43b48ba353b66c4a567873de4dc0fe/license.po#L13

2024-04-23 11:13 UTC, thepetk commented on license.po
> +"Χάρη, στους πολλούς εξωτερικούς εθελοντές που εργάστηκαν κάτω με τις οδηγίες "
```suggestion
"Χάρη, στους πολλούς εξωτερικούς εθελοντές που εργάστηκαν κάτω από τις οδηγίες "
```

2024-04-23 11:14 UTC, thepetk commented
> Άφησα ένα πολύ μικρό suggestion. Επίσης μπορείς να βάλεις τα στοιχεία σου εδώ (αν θελεις):
> 
> https://github.com/pygreece/python-docs-gr/blob/fe868badaf43b48ba353b66c4a567873de4dc0fe/license.po#L13

Όπως και δω

https://github.com/pygreece/python-docs-gr/blob/main/TRANSLATORS

@skpanagiotis

2024-04-23 14:52 UTC, thepetk approved these changes
lgtm

2024-04-24 20:31 UTC, merged