Translate `bugs.po`
pygreece/python-docs-gr pull request #139
Opened 2024-04-23 14:41 UTC by thepetk

## Ποιο issue κλείνει το συγκεκριμένο PR;

Closes https://github.com/pygreece/python-docs-gr/issues/22

## Περιγραφή του PR

Μετάφραση του αρχείου `bugs.po`

2024-04-25 06:24 UTC, skpanagiotis commented on bugs.po
> +"- μπορούν να σταλούν στη διεύθυνση python-list@python.org). Το 'docs@' είναι "
Minor ίσως δεν χρειάζεται η δεύτερη παύλα

2024-04-25 06:33 UTC, skpanagiotis commented on bugs.po
> +"υποβολή σχετικών πληροφοριών και υποβλήθηκε προς τους προγραμματιστές."
```suggestion
"υποβολή σχετικών πληροφοριών στους προγραμματιστές."
```

2024-04-25 06:42 UTC, skpanagiotis commented on bugs.po
> +"ενημέρωση κάθε φορά που το issue θα επεξεργάζεται."
```suggestion
"ενημέρωση κάθε φορά που γίνεται κάποια ενέργεια για το ζήτημα."
```
ή ζήτημα ή προβλημα γιατί στην γραμμή 221 έχει χρησιμοποιήσει τη λέξη πρόβλημα.

2024-04-25 09:38 UTC, thepetk commented on bugs.po
> +"ενημέρωση κάθε φορά που το issue θα επεξεργάζεται."
Πρόβλημα νομίζω καλύτερα

2024-04-29 14:22 UTC, thepetk commented
@skpanagiotis έκανα update το κείμενο

2024-04-30 18:38 UTC, skpanagiotis requested changes

2024-04-30 18:38 UTC, skpanagiotis commented on bugs.po
>  "PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
Ίσως χρειάζεται να συμπληρωθεί η ημερομηνία και η ώρα της τελευταίας αλλάγης για να υπάρχει ένα track.

2024-05-06 10:27 UTC, thepetk commented on bugs.po
>  "PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
@skpanagiotis Done! Καλό catch!

2024-05-06 19:10 UTC, skpanagiotis approved these changes

2024-05-06 19:12 UTC, merged