Translate sphinx.po
pygreece/python-docs-gr pull request #153
Opened 2024-04-25 21:23 UTC by skpanagiotis

## Ποιο issue κλείνει το συγκεκριμένο PR;

Closes #25

## Περιγραφή του PR

Μετάφραση του αρχείου sphinx.po

2024-04-29 14:17 UTC, thepetk requested changes

2024-04-29 14:17 UTC, thepetk commented on sphinx.po
> +"Καλώς ήρθατε! Αυτό είναι η επίσημη τεκμηρίωση για την Python %(release)s."
Νομίζω καλό είναι να μπει στην ίδια γραμμη.

2024-04-29 14:17 UTC, thepetk commented on sphinx.po
> +"ή <a href=\"%(whatsnew_index)s\">όλα \"Τι νέο υπάρχει\" documents</a> από 2.0"
Μου ακούγεται καλύτερο
```suggestion
"ή <a href=\"%(whatsnew_index)s\">όλα \"Τι νέο υπάρχει\" έγγραφα</a> από 2.0"
```

2024-04-29 14:17 UTC, thepetk commented on sphinx.po
> +msgstr "κρατήστε αυτό κάτω από το μαξιλάρι σας"
```suggestion
msgstr "κρατήστε αυτό κατά νου"
```

2024-04-29 14:17 UTC, thepetk commented on sphinx.po
> +msgstr "κρατήστε αυτό κάτω από το μαξιλάρι σας"
Ελπίζω να είναι εκφραση αυτό :D

2024-04-29 14:17 UTC, thepetk commented on sphinx.po
> +msgstr "Εγκατάσταση λειτουργικών μονάδων Python"
```suggestion
msgstr "Εγκατάσταση Python Modules"
```

2024-04-29 14:17 UTC, thepetk commented on sphinx.po
> +msgstr "Διανομή λειτουργικών μονάδων Python"
```suggestion
msgstr "Διανομή Python Modules"
```

2024-04-29 14:17 UTC, thepetk commented on sphinx.po
> +msgstr "δημοσίευση λειτουργικών μονάδων για εγκατάσταση από άλλους"
```suggestion
msgstr "δημοσίευση modules για εγκατάσταση από άλλους"
```

2024-04-29 14:17 UTC, thepetk commented on sphinx.po
> +msgstr "Παγκόσμιο Ευρετήριο Λειτουργικών Μονάδων"
Αυτό θα το άφηνα έτσι
```suggestion
msgstr "Global Module Index"
```

2024-04-29 14:17 UTC, thepetk commented on sphinx.po
> +msgstr "γρήγορη πρόσβαση σε όλες τις λειτουργικές μονάδες"
```suggestion
msgstr "γρήγορη πρόσβαση σε όλες τα modules"
```

2024-04-29 14:17 UTC, thepetk commented on sphinx.po
> +msgstr "Γενικός Ευρετήριο"
```suggestion
msgstr "Γενικό Index"
```

2024-04-29 14:17 UTC, thepetk commented on sphinx.po
> +msgstr "Μεταπληροφορίες:"
```suggestion
msgstr "Μετα-πληροφορίες:"
```

2024-04-29 14:17 UTC, thepetk commented on sphinx.po
> +msgstr "Συμβολή στα Έγγραφα"
```suggestion
msgstr "Συμβολή στην Τεκμηρίωση"
```

2024-04-29 14:17 UTC, thepetk commented on sphinx.po
> +"Αυτή είναι μια προεπισκόπηση ανάπτυξης που δημιουργήθηκε ένα <a "
```suggestion
"Αυτή είναι μια προεπισκόπηση deploy που δημιουργήθηκε από ένα <a "
```

2024-05-08 06:20 UTC, skpanagiotis commented on sphinx.po
> +"Καλώς ήρθατε! Αυτό είναι η επίσημη τεκμηρίωση για την Python %(release)s."
Το βάζει αυτόματα το powrap από κάτω.

2024-05-08 09:34 UTC, thepetk approved these changes
lgtm

2024-05-08 09:35 UTC, merged