Implement create_issues script
pygreece/python-docs-gr pull request #18
Opened 2024-03-31 14:03 UTC by thepetk

## Ποιο issue κλείνει το συγκεκριμένο PR;

Closes https://github.com/pygreece/python-docs-gr/issues/7

## Περιγραφή του PR

Το PR εισάγει ένα script το οποίο μπορεί να χρησιμοποιηθεί (τοπικά) για την δημιουργία όλων των απαραίτητων issues της μετάφρασης μιας έκδοσης της Python

2024-04-02 13:56 UTC, lysnikolaou requested changes
Σιγουρα χρειαζεται η αλλαγη στο `GITHUB_MVP_MILESTONE`. Τα υπολοιπα ειναι περισσοτερο στυλιστικα.

2024-04-02 13:56 UTC, lysnikolaou commented on scripts/create_issues.py
> +import logging
να το ανεβασουμε πανω με τα stdlib imports?

2024-04-02 13:56 UTC, lysnikolaou commented on scripts/create_issues.py
> +GITHUB_MVP_MILESTONE = int(os.getenv("GITHUB_ADDITIONAL_MILESTONE", 2))
```suggestion
GITHUB_MVP_MILESTONE = int(os.getenv("GITHUB_MVP_MILESTONE", 2))
```

2024-04-02 13:56 UTC, lysnikolaou commented on scripts/create_issues.py
> +                filenames.append(os.path.join(path, name).replace(f"{base_path}/", ""))
Αν χρησιμοποιείς 3.12, υπάρχει και το `Path.walk` ([docs](https://docs.python.org/3/library/pathlib.html#pathlib.Path.walk)).

2024-04-02 13:56 UTC, lysnikolaou commented on scripts/create_issues.py
> +            filtered_filenames.append(filename)
```suggestion
        for issue in gh_issues:
            # check if filename is in title AND that the issue is for the same python version
            if filename in issue.title and PYTHON_VERSION in issue.title:
                logging.info(
                    f"Skipping {filename}. There is a similar issue already created at {issue.html_url}"
                )
                break
        else:
            filtered_filenames.append(filename)
```

2024-04-02 13:56 UTC, lysnikolaou commented on scripts/create_issues.py
> +            body=f"""/type translation
μαλλον καλυτερα θα ηταν το body να ειναι καποια constant στην αρχη του αρχειου.

2024-04-02 14:16 UTC, thepetk commented on scripts/create_issues.py
> +            body=f"""/type translation
+1 & Done!

2024-04-04 15:27 UTC, lysnikolaou commented on scripts/create_issues.py
> +                filenames.append(os.path.join(path, name).replace(f"{base_path}/", ""))
οκ, αν εχεις περισσοτερη εμπειρα με το `os.walk`, ας το αφησουμε ετσι!

2024-04-04 15:37 UTC, merged