Translate file faq/programming.po
pygreece/python-docs-gr pull request #515
Opened 2024-05-24 18:04 UTC by skpanagiotis

## Ποιο issue κλείνει το συγκεκριμένο PR;

Closes #27 

## Περιγραφή του PR

Μετάφραση του αρχείου faq/programming.po

2024-05-28 12:20 UTC, thepetk requested changes
@skpanagiotis Έκανα ένα πρώτο pass άφησα κάποια minor comments :)

2024-05-28 12:20 UTC, thepetk commented on faq/programming.po
> +"προσωρινά τις παραμέτρους και την προκύπτουσα τιμή κάθε κλήσης στη συνάρτηση "
```suggestion
"προσωρινά τις παραμέτρους και την επιστρεφόμενη τιμή κάθε κλήσης στη συνάρτηση "
```

2024-05-28 12:20 UTC, thepetk commented on faq/programming.po
>  msgstr ""
Πρώτο pass μέχρι εδω :) Please don't resolve!

2024-06-11 08:42 UTC, thepetk requested changes

2024-06-11 08:42 UTC, thepetk commented on faq/programming.po
> +"παλινδρομήσεων σε εξελιγμένες βελτιστοποιήσεις."
```suggestion
"παλινδρομήσεων (regressions) σε εξελιγμένες βελτιστοποιήσεις."
```

2024-06-11 08:42 UTC, thepetk commented on faq/programming.po
> +"σίγουρα δεν είναι αυτό που θέλετε."
Δεύτερο pass μέχρι εδω! Please don't resolve

2024-06-12 06:14 UTC, skpanagiotis commented on faq/programming.po
> +"Για πιο περίπλοκη ανάλυση εισόδου, οι regular expressions είναι πιο ισχυρές "
Μου κάνει περισσοτερο ως ουδέτερο, αλλά το αλλάζουμε, Το καταλαβαίνω ότι το πάς σαν "οι εκφράσεις", αλλά όταν το κάνουμε στα αγγλικά συνήθως το θεωρούμε ως ουδέτερο.

2024-06-12 08:19 UTC, thepetk commented on faq/programming.po
> +"Για πιο περίπλοκη ανάλυση εισόδου, οι regular expressions είναι πιο ισχυρές "
@skpanagiotis το suggestion ειναι να γίνει ουδέτερο όμως. Δεν κατάλαβα ακριβώς τι εννοείς.

2024-06-12 08:55 UTC, thepetk requested changes
Επιτέλους τέλος :D

2024-06-12 08:55 UTC, thepetk commented on faq/programming.po
> +"Αυτό δημιουργεί μια λίστα που περιέχει 3 διαφορετικές λίστες μήκους δύο.  "
```suggestion
"Αυτό δημιουργεί μια λίστα που περιέχει 3 διαφορετικές λίστες με μήκος δύο.  "
```

2024-06-12 08:55 UTC, thepetk commented on faq/programming.po
> +"δεδομένων μήτρας∙ Το `NumPy <https://numpy.org/>`_ είναι το πιο γνωστό."
```suggestion
"δεδομένων μήτρας (matrix)∙ Το `NumPy <https://numpy.org/>`_ είναι το πιο γνωστό."
```

2024-06-12 08:55 UTC, thepetk commented on faq/programming.po
> +msgstr "Οι τάξεις μπορούν να χρησιμοποιηθούν έτσι:"
```suggestion
msgstr "Οι κλάσσεις μπορούν να χρησιμοποιηθούν έτσι:"
```

2024-06-12 08:55 UTC, thepetk commented on faq/programming.po
> +"την ερμηνεία του ``foo`` και το παγκόσμιο λεξικό συμβόλων για το ``foo`` "
```suggestion
"την ερμηνεία του ``foo`` και το global λεξικό συμβόλων για το ``foo`` "
```

2024-06-13 08:26 UTC, thepetk approved these changes
/lgtm

2024-06-17 13:32 UTC, merged