Translate file tutorial/interactive.po
pygreece/python-docs-gr pull request #517
Opened 2024-05-29 20:43 UTC by skpanagiotis

## Ποιο issue κλείνει το συγκεκριμένο PR;

Closes #50 

## Περιγραφή του PR

Μετάφραση του αρχείου `tutorial/interactive.po`

2024-05-31 08:46 UTC, thepetk requested changes
@skpanagiotis άφησα κάποια πολύ minor suggestions. Σαν γενική παρατήρηση νομίζω είναι η καλύτερη μετάφραση που έχουμε κάνει μέχρι τώρα. Οπότε πιστεύω πως το συγκεκριμένο είναι παράδειγμα για τα επόμενα αρχεία.

Πιο συγκεκριμένα, βοηθάει πολύ όταν πολύπλοκες λέξεις (πχ interpreter, tabs κτλ) παραμένουν αμετάφραστες και πλαισιώνονται από ελληνικό κείμενο. Προσωπικά το βρήκα πολύ ευανάγνωστο.

2024-05-31 08:46 UTC, thepetk commented on tutorial/interactive.po
> +"interprete, έτσι ώστε το κλειδί :kbd:`Tab` να καλεί τη συνάρτηση "
```suggestion
"interpreter, έτσι ώστε το κλειδί :kbd:`Tab` να καλεί τη συνάρτηση "
```

2024-05-31 08:46 UTC, thepetk commented on tutorial/interactive.po
> +msgstr "Εναλλακτικές λύσεις για τον Διαδραστικό Διερμηνέα"
Νομίζω αφού το έχουμε κρατήσει ως interpreter στο υπόλοιπο κείμενο καλό ειναι να το αφήσουμε έτσι και δω.
```suggestion
msgstr "Εναλλακτικές λύσεις για τον Διαδραστικό Interpreter"
```

2024-05-31 08:46 UTC, thepetk commented on tutorial/interactive.po
> +"προηγούμενες εκδόσεις του διερμηνέα' ωστόσο, απομένουν μερικές επιθυμίες: Θα "
```suggestion
"προηγούμενες εκδόσεις του interpreter' ωστόσο, απομένουν μερικές επιθυμίες: Θα "
```

2024-05-31 08:46 UTC, thepetk commented on tutorial/interactive.po
> +"ολοκλήρωσης μπορεί να χρησιμοποιήσει τον πίνακα συμβόλων του interprete.  Θα "
```suggestion
"ολοκλήρωσης μπορεί να χρησιμοποιήσει τον πίνακα συμβόλων του interpreter.  Θα "
```

2024-05-31 08:46 UTC, thepetk commented on tutorial/interactive.po
> +"Ένα εναλλακτικό βελτιωμένος διαδραστικό interprete που υπάρχει εδώ και "
```suggestion
"Ένας εναλλακτικά βελτιωμένος, διαδραστικός, interpreter που υπάρχει εδώ και "
```

2024-06-01 10:46 UTC, thepetk approved these changes
lgtm

2024-06-03 10:14 UTC, lysnikolaou reviewed
Τέλεια δουλειά! 🎉 

Άφησα μερικά recommendations.

2024-06-03 10:14 UTC, lysnikolaou commented on tutorial/interactive.po
> +"ολοκλήρωσης' να κοιτάζει τα ονόματα δηλώσεων της Python, τις τρέχουσες local "
```suggestion
"ολοκλήρωσης; κοιτάζει τα ονόματα δηλώσεων της Python, τις τρέχουσες τοπικές "
```

2024-06-03 10:14 UTC, lysnikolaou commented on tutorial/interactive.po
> +"μεταβλητές, και τα διαθέσιμα ονόματα του module.  Για dotted εκφράσεις, όπως "
```suggestion
"μεταβλητές, και τα διαθέσιμα ονόματα των modules.  Για dotted εκφράσεις, όπως "
```

2024-06-03 10:14 UTC, lysnikolaou commented on tutorial/interactive.po
> +"συνέχει θα προτείνει συμπληρώσεις από τα χαρακτηριστικά του αντικειμένου που "
```suggestion
"συνέχεια θα προτείνει συμπληρώσεις από τα χαρακτηριστικά του αντικειμένου που "
```

2024-06-03 10:14 UTC, lysnikolaou commented on tutorial/interactive.po
> +"προκύπτει.  Σημειώστε ότι αυτό μπορεί να εκτελέσει που ορίζεται από την "
```suggestion
"προκύπτει.  Σημειώστε ότι αυτό μπορεί να εκτελέσει κώδικα που ορίζεται από την "
```

2024-06-03 10:14 UTC, lysnikolaou commented on tutorial/interactive.po
> +"συνεδρίας διαδραστικού interpreter."
```suggestion
"συνεδρία διαδραστικού interpreter."
```

2024-06-03 10:14 UTC, lysnikolaou commented on tutorial/interactive.po
> +"προηγούμενες εκδόσεις του interpreter' ωστόσο, απομένουν μερικές επιθυμίες: "
```suggestion
"προηγούμενες εκδόσεις του interpreter; ωστόσο, παραμένουν μερικές επιθυμίες: "
```

2024-06-03 10:14 UTC, lysnikolaou commented on tutorial/interactive.po
> +"Ένας εναλλακτικά βελτιωμένος, διαδραστικός, interpreter που υπάρχει εδώ και "
```suggestion
"Ένας εναλλακτικός, βελτιωμένος, διαδραστικός interpreter που υπάρχει εδώ και "
```

2024-06-03 14:14 UTC, skpanagiotis commented on tutorial/interactive.po
> +"ολοκλήρωσης' να κοιτάζει τα ονόματα δηλώσεων της Python, τις τρέχουσες local "
ο χαρακτήρας `;` είναι η άνω τελεία και το έχουμε χρησιμοποιήσει το σύμβολο `'` για είναι πιο φανερό.

2024-06-11 08:31 UTC, merged