WIP: Translate `library/stdtypes.po`
pygreece/python-docs-gr pull request #549
Opened 2024-08-05 11:52 UTC by thepetk

## Ποιο issue κλείνει το συγκεκριμένο PR;

Closes https://github.com/pygreece/python-docs-gr/issues/66

## Περιγραφή του PR

Μεταφράζει το αρχείο `library/stdtypes.po`.

2024-08-05 12:25 UTC, skpanagiotis requested changes
Πολύ καλή μετάφραση και μου αρέσει (κάτι που δεν έχω πολυκάνει) ελληνική λέξη και δίπλα με παρένθεση τα αγγλικά. Έχουνε ξεφύγει μερικά αμετάφραστα, και δεν ξέρω αν είναι σωστό αυτό που έχω προτείνει αρκετά ` λογική (Boolean)`

2024-08-05 12:25 UTC, skpanagiotis commented on library/stdtypes.po
> +"του, για χρήση σε :keyword:`if` :keyword:`while` συνθήκη ή ως τελεστής των "
```suggestion
"του, για χρήση σε :keyword:`if` ή :keyword:`while` συνθήκη ή ως τελεστής των "
```

2024-08-05 12:25 UTC, skpanagiotis commented on library/stdtypes.po
> +"για true, εκτός εάν δηλώνεται διαφορετικά. (Σημαντική εξαίρεση: οι πράξεις "
```suggestion
"για true, εκτός εάν δηλώνεται διαφορετικά. (Σημαντική εξαίρεση: οι λογικές (Boolean) "
```

2024-08-05 12:25 UTC, skpanagiotis commented on library/stdtypes.po
> +"Boolean ``or`` και ``and`` επιστρέφουν πάντα έναν από τους τελεστές τους.)"
```suggestion
"πράξεις ``or`` και ``and`` επιστρέφουν πάντα έναν από τους τελεστές τους.)"
```

2024-08-05 12:25 UTC, skpanagiotis commented on library/stdtypes.po
> +"To ``not`` έχει χαμηλότερη προτεραιότητα από τους non-Bolean τελεστές, οπότε "
```suggestion
"To ``not`` έχει χαμηλότερη προτεραιότητα από τους μη λογικούς (non-Boοlean) τελεστές, οπότε "
```

2024-08-05 12:25 UTC, skpanagiotis commented on library/stdtypes.po
>  msgid "Comparisons"
```suggestion
msgid "Comparisons"
msgstr "Συγκρίσεις"
```
Απλά δεν έχει μεταφραστεί και έκανα το suggestion εκεί δεν μπορούσα πιο κάτω.

2024-08-05 12:25 UTC, skpanagiotis commented on library/stdtypes.po
> +"προτεραιότητα (η οποία είναι υψηλότερη από αυτή των πράξεων Boolean). Οι "
```suggestion
"προτεραιότητα (η οποία είναι υψηλότερη από αυτή των λογικών (Boolean) πράξεων). Οι "
```

2024-08-05 12:25 UTC, skpanagiotis commented on library/stdtypes.po
> +"κλάση ορίζει αρκετές τις μεθόδους :meth:`~object.__lt__`, :meth:`~object."
```suggestion
"κλάση ορίζει αρκετές από τις μεθόδους :meth:`~object.__lt__`, :meth:`~object."
```

2024-08-05 12:25 UTC, skpanagiotis commented on library/stdtypes.po
> +"func:`complex` να παράγουν αριθμούς συγκεκριμένου τύπου."
```suggestion
"func:`complex` για να παράγουν αριθμούς συγκεκριμένου τύπου."
```

2024-08-05 12:51 UTC, thepetk commented on library/stdtypes.po
>  msgid ""
Ναι ναι, γι'αυτο το εχω μαρκαρει σαν WIP

2024-08-05 12:53 UTC, skpanagiotis commented on library/stdtypes.po
>  msgid ""
Ναι μετά το είδα.

2024-08-05 12:54 UTC, thepetk commented
> Πολύ καλή μετάφραση και μου αρέσει (κάτι που δεν έχω πολυκάνει) ελληνική λέξη και δίπλα με παρένθεση τα αγγλικά. Έχουνε ξεφύγει μερικά αμετάφραστα, και δεν ξέρω αν είναι σωστό αυτό που έχω προτείνει αρκετά ` λογική (Boolean)`

Πέρα από τεράστιο, είναι και περίπλοκο το αρχείο γιατί έχει αρκετά μαθηματικά προς μετάφραση. Σχετικά με το φορματ αμεταφραστο/μετεφρασμενο/μετεφρασμενο (αμεταφραστο) το αποφασίζουμε ως μέρος του https://github.com/pygreece/python-docs-gr/issues/538 και το κάνουμε "skip" τωρα σαν out-of-scope.

2024-08-05 12:56 UTC, skpanagiotis commented
Ναι ναι συμφωνώ το βλέπουμε στο revision.

2024-08-05 12:59 UTC, thepetk commented
> Ναι ναι συμφωνώ το βλέπουμε στο revision.

Επίσης δοκίμασα ένα "ημι-αυτοματο" τρόπο με την έννοια λίγο translate λίγο με manual. Νομίζω είναι ξεκάθαρο μετα το review που έκανες ότι θα το συνεχίσω και γω manual. Έχουν ξεφύγει πολύ εύκολα λάθη.

2024-08-16 14:30 UTC, thepetk commented on library/stdtypes.po
> +"χρησιμοποιήστε το :data:`sys.byteorder` ως τιμή της σειράς byte."
Νέα μετάφραση μέχρι εδώ.

2024-09-09 06:25 UTC, skpanagiotis commented on library/stdtypes.po
> +"ρητού αριθμού, :class:`float`, ή :class:`complex`:"
```suggestion
"ρητού αριθμού, :class:`float`, ή :class:`complex`::"
```

2024-09-09 06:26 UTC, skpanagiotis commented on library/stdtypes.po
> +"Οι Booleans αντιπροσωπεύουν τιμές αλήθειας. Ο τύπος :class:`bool` έχει "
```suggestion
"Οι δυαδικές τιμές (Booleans) αντιπροσωπεύουν τιμές αλήθειας. Ο τύπος :class:`bool` έχει "
```

2024-09-09 06:26 UTC, skpanagiotis commented on library/stdtypes.po
> +"boolean, αν η τιμή μπορεί να ερμηνευτεί ως τιμή αλήθειας (βλέπε παραπάνω "
```suggestion
"δυαδική (boolean), αν η τιμή μπορεί να ερμηνευτεί ως τιμή αλήθειας (βλέπε παραπάνω "
```

2024-09-09 06:28 UTC, skpanagiotis commented on library/stdtypes.po
> +"raise ένα σφάλμα στην Python 3.14."
Μήπως το *raise* το κάναμε δημιουργεί;

2024-09-09 06:30 UTC, skpanagiotis commented on library/stdtypes.po
> +"βασίζεστε σε αυτό· μετατρέψτε χρησιμοποιώντας το :func:`int` αντ' αυτού."
```suggestion
"βασίζεστε σε αυτό· πιο αναλυτικά κάντε μετατροπή χρησιμοποιώντας τη :func:`int` αντ' αυτού."
```

2024-09-09 06:33 UTC, skpanagiotis commented on library/stdtypes.po
> +"μέθοδος αντιστοιχεί στην στην δομή :c:member:`~PyTypeObject.tp_iternext` των "
```suggestion
"μέθοδος αντιστοιχεί στην δομή :c:member:`~PyTypeObject.tp_iternext` των "
```

2024-09-09 06:33 UTC, skpanagiotis commented on library/stdtypes.po
> +"συγκεκριμένοι τύποι δεν είναι σημαντικοί πέρα από την υλοποίησή του του "
```suggestion
"συγκεκριμένοι τύποι δεν είναι σημαντικοί πέρα από την υλοποίησή του "
```

2024-09-09 06:34 UTC, skpanagiotis commented on library/stdtypes.po
> +"Μόλις η μέθοδος :meth:`~iterator.__next__` ενός iterator κάνει raise ένα :"
Το ίδιο που ανέφερα παραπάνω για το *raise*

2024-09-09 06:35 UTC, skpanagiotis commented on library/stdtypes.po
> +"διευκολύνει τη σωστή υλοποίηση αυτών των πράξεων σε προσαρμοσμένες τύπους "
```suggestion
"διευκολύνει τη σωστή υλοποίηση αυτών των πράξεων σε προσαρμοσμένους τύπους "
```

2024-09-09 06:38 UTC, skpanagiotis commented on library/stdtypes.po
> +"`IndexError` ή ένα :exc:`StopIteration` γίνει raise (ή όταν ο δείκτης πέσει "
Πάλι το σχόλιο για την αντικαστάστση του raise με δημιουργεί

2024-09-09 06:45 UTC, skpanagiotis commented on library/stdtypes.po
> +msgstr "αφαιρεί του πρώτου στοιχείου από το *s* όπου ``s[i]`` είναι ίσο με *x*"
```suggestion
msgstr "αφαιρεί το πρώτο στοιχείο από το *s* όπου ``s[i]`` είναι ίσο με *x*"
```

2024-09-09 06:49 UTC, skpanagiotis commented on library/stdtypes.po
> +"η *reverse* είναι μια boolean τιμή.  Αν τεθεί σε ``True``, τότε τα στοιχεία "
```suggestion
"η *reverse* είναι μια δυαδική (boolean) τιμή.  Αν τεθεί σε ``True``, τότε τα στοιχεία "
```

2024-09-09 06:51 UTC, skpanagiotis requested changes
Μου αρέσει πως διαχειρίζεσαι το ποιες θα αφήσεις αμετάφραστες, μεταφρασμένες και αυτές με παρένθεση δίπλα.

2024-09-09 07:43 UTC, thepetk commented on library/stdtypes.po
> +"η *reverse* είναι μια boolean τιμή.  Αν τεθεί σε ``True``, τότε τα στοιχεία "
`Λογική` ίσως καλύτερα;

2024-09-09 07:45 UTC, thepetk commented on library/stdtypes.po
> +"raise ένα σφάλμα στην Python 3.14."
Χωρίς κάποιο strong preference, ο μόνος λόγος που κρατάω το raise είναι για να συνηθίσει ο αναγνώστης στην έννοια του αφού αποτελεί σημαντικό κομμάτι της Python. Νομίζω όπως και αν αποφασίσουμε να το έχουμε καλό είναι να το βάλουμε παντού το ίδιο.

2024-09-09 10:33 UTC, thepetk commented on library/stdtypes.po
> +"raise ένα σφάλμα στην Python 3.14."
@skpanagiotis just to confirm οτι θα κρατήσουμε το "κάνει raise".

2024-10-29 16:01 UTC, thepetk reviewed
Τρομερή δουλειά!

Έκανα ένα pass, αλλά το κείμενο είναι τεράστιο άρα και το review πολύ δύσκολο. Προτείνω να το mergαρουμε και βλεπουμε στην πορεία με sub-issues τυχόν διορθώσεις που μπορεί να χρειαστούν.

2024-10-30 07:26 UTC, skpanagiotis commented on library/stdtypes.po
> +"Τα αντικείμενα ``GenericAlias`` είναι στιγμιότυπα της κλάσης :class:`types."
Διαφωνώ, είναι κάτι που πιστεύω είμαστε εξοικιωμένοι, και αρκετοί το διαδάκουν ως στιγμιοτυπο σε μαθήματα που έχουν να κάνουνε με αντικειμενοστρεφή προγραμματισμό.

2024-10-30 07:27 UTC, skpanagiotis commented on library/stdtypes.po
> +msgstr "Όψεις Μνήμης"
Το συγκεκριμένο το μετάφρασα επηρεασμένος και από άλλες μεταφράσεις.

2024-10-30 20:30 UTC, skpanagiotis requested changes

2024-10-30 20:30 UTC, skpanagiotis commented on library/stdtypes.po
> +"(consistency) με τα interfaces των μεταβλητών container που δεν υποστηρίζουν "
νομίζω ότι είναι αχρείαστο
```suggestion
"με τα interfaces των μεταβλητών container που δεν υποστηρίζουν "
```

2024-10-30 20:30 UTC, skpanagiotis commented on library/stdtypes.po
> +"λειτουργίες τεμαχισμού (όπως τα :class:`dict` και :class:`set`). Η :meth:`!"
```suggestion
"λειτουργίες τμηματοποίησης (όπως τα :class:`dict` και :class:`set`). Η :meth:`!"
```

2024-10-30 20:30 UTC, skpanagiotis commented on library/stdtypes.po
> +"είναι τα ίδια και με την ίδια σειρά όπως τα στοιχεία της *iterable*.  Η "
```suggestion
"είναι τα ίδια και με την ίδια σειρά όπως τα στοιχεία του *iterable*.  Το "
```

2024-10-30 20:30 UTC, skpanagiotis commented on library/stdtypes.po
> +msgstr "Tuples (Πλειάδες)"
```suggestion
msgstr "Πλειάδες (Tuples)"
```

2024-10-30 20:30 UTC, skpanagiotis commented on library/stdtypes.po
> +"Τα tuples (πλειάδες) είναι αμετάβλητες ακολουθίες, που συνήθως "
```suggestion
"Οι πλειάδες (tuples) είναι αμετάβλητες ακολουθίες, που συνήθως "
```

2024-10-30 20:30 UTC, skpanagiotis commented on library/stdtypes.po
> +msgstr "Τα tuples (πλειάδες) μπορούν να κατασκευαστούν με διάφορους τρόπους:"
```suggestion
msgstr "Οι πλειάδες (tuples) μπορούν να κατασκευαστούν με διάφορους τρόπους:"
```

2024-10-30 20:30 UTC, skpanagiotis commented on library/stdtypes.po
> +"Ο κατασκευαστής (constructor) δημιουργεί ένα tuple (πλειάδα) του οποίου τα "
```suggestion
"Ο κατασκευαστής (constructor) δημιουργεί μια πλειάδα (tuple) του οποίου τα "
```

2024-10-30 20:30 UTC, skpanagiotis commented on library/stdtypes.po
> +msgstr "Ranges (Εύρη)"
```suggestion
msgstr "Εύρη (Ranges)"
```

2024-10-30 20:30 UTC, skpanagiotis commented on library/stdtypes.po
> +"Τα ορίσματα του range constructor (κατασκευαστή εύρους) πρέπει να είναι "
```suggestion
"Τα ορίσματα του  κατασκευαστή εύρους (range constructor) πρέπει να είναι "
```

2024-10-30 20:30 UTC, skpanagiotis commented on library/stdtypes.po
> +"*step* παραλείπεται, το default (προεπιλογή) είναι ``1``. Εάν το όρισμα "
```suggestion
"*step* παραλείπεται, το προεπιλογή (default) είναι ``1``. Εάν το όρισμα "
```

2024-10-30 20:30 UTC, skpanagiotis commented on library/stdtypes.po
> +"*start* παραλείπεται, το default (προεπιλογή) είναι ``0``. Εάν το *step* "
```suggestion
"*start* παραλείπεται, το προεπιλογή (default) είναι ``0``. Εάν το *step* "
```

2024-10-30 20:30 UTC, skpanagiotis commented on library/stdtypes.po
> +"Για ένα αρνητικό *βήμα*, τα περιεχόμενα του range (εύρους) εξακολουθούν να "
```suggestion
"Για ένα αρνητικό *βήμα*, τα περιεχόμενα του εύρους (range) εξακολουθούν να "
```

2024-10-30 20:30 UTC, skpanagiotis commented on library/stdtypes.po
> +"Υλοποιείστε την ακολουθία ABC. Υποστηρίξτε τον τεμαχισμό και τους αρνητικούς "
```suggestion
"Υλοποιείστε την ακολουθία ABC. Υποστηρίξτε την τμηματοποίηση και τους αρνητικούς "
```

2024-10-30 20:30 UTC, skpanagiotis commented on library/stdtypes.po
> +"τέλος της ουράς. Για παράδειγμα: "
Πέρασμα μέχρι εδώ

2024-10-31 13:31 UTC, skpanagiotis requested changes

2024-10-31 13:31 UTC, skpanagiotis commented on library/stdtypes.po
> +"να είναι ένα αντικείμενο που υλοποιεί το indexing μέσω της :meth:`~object."
```suggestion
"να είναι ένα αντικείμενο που υλοποιεί ευρετηριοποίηση μέσω της :meth:`~object."
```

2024-10-31 13:31 UTC, skpanagiotis commented on library/stdtypes.po
> +"ένα χάρτη μετάφρασης από χαρακτήρα-σε-χαρακτήρα mappings σε διαφορετικές "
```suggestion
"ένα χάρτη μετάφρασης αντιστοίχισης από χαρακτήρα-σε-χαρακτήρα σε διαφορετικές "
```

2024-10-31 13:31 UTC, skpanagiotis commented on library/stdtypes.po
> +"τους δικούς τους συμβιβασμούς και τα οφέλη της απλότητας, ευελιξίας και/ή "
```suggestion
"τους δικούς τις συμβιβασμούς και τα οφέλη της απλότητας, ευελιξίας και/ή "
```

2024-10-31 13:31 UTC, skpanagiotis commented on library/stdtypes.po
> +"από το format string ή ένα μεμονωμένο αντικείμενο mapping (για παράδειγμα, "
```suggestion
"από το format string ή ένα μεμονωμένο αντικείμενο αντιστοίχισης (για παράδειγμα, "
```

2024-10-31 13:31 UTC, skpanagiotis commented on library/stdtypes.po
> +"Ένας conversion specifier περιέχει δύο ή περισσότερους χαρακτήρες και έχει "
```suggestion
"Ένας προσδιοριστής μετατροπής περιέχει δύο ή περισσότερους χαρακτήρες και έχει "
```

2024-10-31 13:31 UTC, skpanagiotis commented on library/stdtypes.po
> +msgstr "Ο χαρακτήρας ```%''``, που σηματοδοτεί την αρχή του specifier."
```suggestion
msgstr "Ο χαρακτήρας ```%''``, που σηματοδοτεί την αρχή του προσδιοριστή."
```

2024-10-31 13:31 UTC, skpanagiotis commented on library/stdtypes.po
> +"Σημαίες conversion (προαιρετικό), που επηρεάζουν το αποτέλεσμα κάποιων τύπων "
```suggestion
"Δείκτες μετατροπής (προαιρετικό), που επηρεάζουν το αποτέλεσμα κάποιων τύπων "
```

2024-10-31 13:31 UTC, skpanagiotis commented on library/stdtypes.po
> +"conversion."
```suggestion
"μετατροπής."
```

2024-10-31 13:31 UTC, skpanagiotis commented on library/stdtypes.po
> +"Precision (προαιρετικό), δίνεται ως ``'.'`` (τελεία) ακολουθούμενη από το "
```suggestion
"Ακρίβεια (προαιρετικό), δίνεται ως ``'.'`` (τελεία) ακολουθούμενη από το "
```

2024-11-01 07:56 UTC, merged

2024-11-02 00:30 UTC, thepetk commented
Thanks a ton @skpanagiotis for the H U G E help on this one!