Translate library/functions
pygreece/python-docs-gr pull request #551
Opened 2024-09-07 15:20 UTC by skpanagiotis

## Ποιο issue κλείνει το συγκεκριμένο PR;

Closes #67 

## Περιγραφή του PR

Μετάφραση του αρχείου library/functions.po

2024-09-08 15:48 UTC, thepetk reviewed
Δύσκολο κείμενο..

Άφησα κάποια suggestions για τα `raise`, `instance` και `container` με βάσει την μετάφραση για το stdtypes.po και πως τα έχω βάλει εκεί. Σύμφωνα με ότι αποφασίσουμε εδώ, θα τα κάνω update και εκεί!

2024-09-08 15:48 UTC, thepetk commented on library/functions.po
> +msgstr "Ενσωματωμένες Συναρτήσεις"
Σε όσα έχω μεταφράσει μέχρι στιγμής το κρατάω και το built-in γιατί είναι ένας όρος που συναντάει κάποιος συχνά στην Python. Μπορούμε να το βάλουμε και σε παρενθεση κάπως έτσι. Πως σου φαίνεται;

```suggestion
msgstr "Ενσωματωμένες (Built-in) Συναρτήσεις"
```

2024-09-08 15:48 UTC, thepetk commented on library/functions.po
> +"ενσωματωμένους σε αυτόν, που είναι πάντα διαθέσιμα.  Παρατίθενται εδώ με "
```suggestion
"ενσωματωμένους (built-in) σε αυτόν, που είναι πάντα διαθέσιμα.  Παρατίθενται εδώ με "
```

2024-09-08 15:48 UTC, thepetk commented on library/functions.po
> +"Επιστρέφει την απόλυτη τιμή ενός αριθμού. Το όρισμα μπορεί να είναι ένα "
```suggestion
"Επιστρέφει την απόλυτη τιμή ενός αριθμού. Το όρισμα μπορεί να είναι ένας "
```

2024-09-08 15:48 UTC, thepetk commented on library/functions.po
> +"το :meth:`~object.__abs__`. Εάν το όρισμα είναι ένας περίπλοκος αριθμός "
Με επιφυλακτικότητα, νομίζω πως εννοεί την method `__abs__`
```suggestion
"την :meth:`~object.__abs__`. Εάν το όρισμα είναι ένας περίπλοκος αριθμός "
```

2024-09-08 15:48 UTC, thepetk commented on library/functions.po
> +"Επιστρέφεται ένας :term:`asynchronous iterator` για έναν :term:`asynchronous "
```suggestion
"Επιστρέφεται ένας :term:`asynchronous iterator` για ένα :term:`asynchronous "
```

2024-09-08 15:48 UTC, thepetk commented on library/functions.po
> +"Σημείωση: Σε αντίθεση με το :func:`iter`, :func:`aiter` δεν έχει παραλλαγή 2 "
```suggestion
"Σημείωση: Σε αντίθεση με το :func:`iter`, το :func:`aiter` δεν έχει παραλλαγή 2 "
```

2024-09-08 15:48 UTC, thepetk commented on library/functions.po
> +"Επιστρέφετε ένας νέος πίνακα από bytes.  Η κλάση :class:`bytearray` είναι "
```suggestion
"Επιστρέφετε ένας νέος πίνακας από bytes.  Η κλάση :class:`bytearray` είναι "
```

2024-09-08 15:48 UTC, thepetk commented on library/functions.po
> +"Επιστρέφετε ένα νέο αντικείμενο \"bytes\", που είναι μια αμετάβλητη "
```suggestion
"Επιστρέφεται ένα νέο αντικείμενο \"bytes\", που είναι μια αμετάβλητη "
```

2024-09-08 15:48 UTC, thepetk commented on library/functions.po
> +"Συνεπώς, τα ορίσματα του constructor γίνονται ερμηνεύονται ως :func:"
```suggestion
"Συνεπώς, τα ορίσματα του constructor ερμηνεύονται ως :func:"
```

2024-09-08 15:48 UTC, thepetk commented on library/functions.po
> +"μιας κλάσης επιστρέφει ένα νέο στιγμιότυπο). Τα στιγμιότυπα μπορούν να "
```suggestion
"μιας κλάσης επιστρέφει ένα νέο instance). Τα instances μπορούν να "
```

2024-09-08 15:48 UTC, thepetk commented on library/functions.po
> +"16).  Το :exc:`ValueError` θα εγειρθεί εάν το *i* είναι εκτός αυτού του "
Όπως και στο instances και εδώ νομίζω το raise ίσως να ήταν καλύτερο να μείνει αμετάφραστο μιας και χρησιμοποιείται πολύ συχνα.
```suggestion
"16).  Το :exc:`ValueError` θα γίνει raise εάν το *i* είναι εκτός αυτού του "
```

2024-09-08 15:48 UTC, thepetk commented on library/functions.po
> +"ένα στιγμιότυπο (όπως ``C().f()``).  Το στιγμιότυπο αγνοείται εκτός από την "
```suggestion
"ένα instance (όπως ``C().f()``).  Το instance αγνοείται εκτός από την "
```

2024-09-08 15:48 UTC, thepetk commented on library/functions.po
> +"Εγείρει ένα :ref:`auditing event <auditing>` ``compile`` με ορίσματα "
```suggestion
"Κάνει raise ένα :ref:`auditing event <auditing>` ``compile`` με ορίσματα "
```

2024-09-08 15:48 UTC, thepetk commented on library/functions.po
> +"Εγείρει ένα :ref:`auditing event <auditing>` ``compile`` με ορίσματα "
```suggestion
"Κάνει raise ένα :ref:`auditing event <auditing>` ``compile`` με ορίσματα "
```

2024-09-08 15:48 UTC, thepetk commented on library/functions.po
> +"Είναι δυνατό να καταρρεύσει ο interpreter της Python με μια αρκετά μεγάλη/"
Έδω σκέφτομαι κάτι εναλλακτικό για το crash

2024-09-08 15:48 UTC, thepetk commented on library/functions.po
> +"Για άλλα κοντέινερ, δείτε τις ενσωματωμένες κλάσεις :class:`list`, :class:"
Αυτό το κρατάω και γω αμεταφραστο απλά στα αγγλικά.
```suggestion
"Για άλλα containers, δείτε τις ενσωματωμένες κλάσεις :class:`list`, :class:"
```

2024-09-08 15:48 UTC, thepetk commented on library/functions.po
> +"Εάν το αντικείμενο δεν παρέχει :meth:`~object.__dir__`, η συνάρτηση "
```suggestion
"Εάν το αντικείμενο δεν παρέχει την :meth:`~object.__dir__`, η συνάρτηση "
```

2024-09-08 15:48 UTC, thepetk commented on library/functions.po
> +"Επειδή η :func:`dir` παρέχεται κυρίως ως ευκολία για χρήση σε μια "
Πρώτο pass μέχρι εδώ!

2024-09-08 18:15 UTC, skpanagiotis commented on library/functions.po
> +"Εγείρει ένα :ref:`auditing event <auditing>` ``compile`` με ορίσματα "
Τσέκαρα λίγο και στην ισπανική μετάφραση τι μεταφράζουνε και τι όχι. Αυτό με το exception το έχω μεταφράσει σε σημεία και ως εγείρει και ως δημιουργεί.

2024-09-11 11:50 UTC, thepetk requested changes
Τεράστιο αρχείο :D Ήρωας!

2024-09-11 11:50 UTC, thepetk commented on library/functions.po
> +"Επιστρέφετε ένα αντικείμενο απαρίθμησης.  Το *iterable* πρέπει να είναι μια "
Αυτό το `return` με προβληματίζει πολύ. Εγώ καταλαβαίνω ότι εννοεί returns έτσι όπως το μεταφράζω.
```suggestion
"Επιστρέφει ένα αντικείμενο απαρίθμησης.  Το *iterable* πρέπει να είναι μια "
```

2024-09-11 11:50 UTC, thepetk commented on library/functions.po
> +"Τα ορίσματα είναι μια συμβολοσειρά, και προαιρετικά globals και locals.  Εάν "
```suggestion
"Τα ορίσματα είναι μια συμβολοσειρά (string), και προαιρετικά globals και locals.  Εάν "
```

2024-09-11 11:50 UTC, thepetk commented on library/functions.po
> +"(από τεχνικής άποψης, μια λίστα συνθηκών) χρησιμοποιώντας τα λεξικά "
```suggestion
"(από τεχνικής άποψης, μια λίστα συνθηκών) χρησιμοποιώντας τα λεξικά (dictionaries) "
```

2024-09-11 11:50 UTC, thepetk commented on library/functions.po
> +"Εγείρει ένα :ref:`auditing event <auditing>` ``exec`` με όρισμα "
```suggestion
"Κάνει raise ένα :ref:`auditing event <auditing>` ``exec`` με όρισμα "
```

2024-09-11 11:50 UTC, thepetk commented on library/functions.po
> +"Εγείρει ένα :ref:`auditing event <auditing>` ``exec`` με το αντικείμενο "
```suggestion
"Κάνει raise ένα :ref:`auditing event <auditing>` ``exec`` με το αντικείμενο "
```

2024-09-11 11:50 UTC, thepetk commented on library/functions.po
> +"πρέπει να είναι είτε μια συμβολοσειρά είτε ένα αντικείμενο κώδικα.  Εάν "
```suggestion
"πρέπει να είναι είτε μια συμβολοσειρά (string) είτε ένα αντικείμενο κώδικα.  Εάν "
```

2024-09-11 11:50 UTC, thepetk commented on library/functions.po
> +"ενσωματωμένα είναι διαθέσιμα στον εκτελέσιμο κώδικα εισάγοντας το δικό σας "
```suggestion
"ενσωματωμένα (built-ins) είναι διαθέσιμα στον εκτελέσιμο κώδικα εισάγοντας το δικό σας "
```

2024-09-11 11:50 UTC, thepetk commented on library/functions.po
> +"Εάν το όρισμα είναι συμβολοσειρά, θα πρέπει να περιέχει έναν δεκαδικό "
```suggestion
"Εάν το όρισμα είναι συμβολοσειρά (string), θα πρέπει να περιέχει έναν δεκαδικό "
```

2024-09-11 11:50 UTC, thepetk commented on library/functions.po
> +"Τα πεζά δεν είναι σημαντικά, επομένως, για παράδειγμα, \"inf\", \"Inf\", "
```suggestion
"Τα πεζά/κεφαλαία δεν είναι σημαντικά, επομένως, για παράδειγμα, \"inf\", \"Inf\", "
```

2024-09-11 11:50 UTC, thepetk commented on library/functions.po
> +"του εύρους ενός float της Python θα εμφανιστεί ένα :exc:`OverflowError`."
```suggestion
"του εύρους ενός float της Python θα γίνει raise ένα :exc:`OverflowError`."
```

2024-09-11 11:50 UTC, thepetk commented on library/functions.po
> +"Τα ορίσματα είναι ένα αντικείμενο και μια συμβολοσειρά.  Το αποτέλεσμα είναι "
```suggestion
"Τα ορίσματα είναι ένα αντικείμενο και μια συμβολοσειρά (string).  Το αποτέλεσμα είναι "
```

2024-09-11 11:50 UTC, thepetk commented on library/functions.po
> +"Καλείται το ενσωματωμένο σύστημα βοήθειας.  (Αυτή η συνάρτηση προορίζεται "
```suggestion
"Καλείται το ενσωματωμένο (built-in) σύστημα βοήθειας.  (Αυτή η συνάρτηση προορίζεται "
```

2024-09-11 11:50 UTC, thepetk commented on library/functions.po
> +"Μετατροπή ενός ακεραίου αριθμού σε μια πεζή δεκαεξαδική συμβολοσειρά με "
```suggestion
"Μετατροπή ενός ακεραίου αριθμού σε μια πεζή δεκαεξαδική συμβολοσειρά (string) με "
```

2024-09-11 11:50 UTC, thepetk commented on library/functions.po
> +"δεκαεξαδική συμβολοσειρά με πρόθεμα ή όχι, μπορείτε να χρησιμοποιήσετε έναν "
```suggestion
"δεκαεξαδική συμβολοσειρά (string) με πρόθεμα ή όχι, μπορείτε να χρησιμοποιήσετε έναν "
```

2024-09-11 11:50 UTC, thepetk commented on library/functions.po
> +"γραμμής) και την επιστρέφει.  Όταν διαβάζεται το EOF, εγείρεται :exc:"
```suggestion
"γραμμής) και την επιστρέφει.  Όταν διαβάζεται το EOF, γίνεται raise :exc:"
```

2024-09-11 11:50 UTC, thepetk commented on library/functions.po
> +"Εγείρει ένα :ref:`auditing event <auditing>` ``builtins.input`` με όρισμα "
```suggestion
"Κάνει raise ένα :ref:`auditing event <auditing>` ``builtins.input`` με όρισμα "
```

2024-09-11 11:50 UTC, thepetk commented on library/functions.po
> +"Εγείρει ένα :ref:`auditing event <auditing>` ``builtins.input`` με όρισμα "
```suggestion
"Κάνει raise  ένα :ref:`auditing event <auditing>` ``builtins.input`` με όρισμα "
```

2024-09-11 11:50 UTC, thepetk commented on library/functions.po
> +"Εγείρει ένα :ref:`auditing event <auditing>` ``builtins.input/result`` με "
```suggestion
"Κάνει raise  ένα :ref:`auditing event <auditing>` ``builtins.input/result`` με "
```

2024-09-11 11:50 UTC, thepetk commented on library/functions.po
> +"Εγείρει ένα :ref:`auditing event <auditing>` ``builtins.input/result`` με το "
```suggestion
"Κάνει raise  ένα :ref:`auditing event <auditing>` ``builtins.input/result`` με το "
```

2024-09-11 11:50 UTC, thepetk commented on library/functions.po
> +"Επιστρέφετε ``True`` εάν η *class* είναι μια υποκλάση (άμεση, έμμεση, ή :"
```suggestion
"Επιστρέφει ``True`` εάν η *class* είναι μια υποκλάση (άμεση, έμμεση, ή :"
```

2024-09-11 11:50 UTC, thepetk commented on library/functions.po
> +"υποκλάση του εαυτού της. Το *classinfo* μπορεί να είναι μια πλειάδα "
```suggestion
"υποκλάση του εαυτού της. Το *classinfo* μπορεί να είναι μια πλειάδα (tuple) "
```

2024-09-11 11:50 UTC, thepetk commented on library/functions.po
> +msgstr "άνοιγμα για ανάγνωση (προεπιλογή)"
```suggestion
msgstr "άνοιγμα για ανάγνωση (default)"
```

2024-09-11 11:50 UTC, thepetk commented on library/functions.po
> +msgstr "δυαδική λειτουργία"
```suggestion
msgstr "δυαδική (binary) λειτουργία"
```

2024-09-11 11:50 UTC, thepetk commented on library/functions.po
> +"\"Διαδραστικά\" αρχεία κειμένου (αρχεία για τα οποία το :meth:`~io.IOBase."
```suggestion
"\"Interactive\" αρχεία κειμένου (αρχεία για τα οποία το :meth:`~io.IOBase."
```

2024-09-11 11:50 UTC, thepetk commented on library/functions.po
> +"εγείρει μια εξαίρεση :exc:`InterruptedError` (δείτε το :pep:`475` για το "
```suggestion
"κάνει raise μια εξαίρεση :exc:`InterruptedError` (δείτε το :pep:`475` για το "
```

2024-09-11 11:50 UTC, thepetk commented on library/functions.po
> +"πρέπει να δίνονται ως ορίσματα λέξης-κλειδί."
```suggestion
"πρέπει να δίνονται ως ορίσματα keyword."
```

2024-09-11 11:50 UTC, thepetk commented on library/functions.po
> +"Όλα τα ορίσματα μη λέξεων-κλειδιών μετατρέπονται σε συμβολοσειρές όπως κάνει "
```suggestion
"Όλα τα μη keyword ορίσματα μετατρέπονται σε συμβολοσειρές όπως κάνει "
```

2024-09-11 11:50 UTC, thepetk commented on library/functions.po
> +msgstr "Προστέθηκε το όρισμα λέξης-κλειδιού *flush*."
```suggestion
msgstr "Προστέθηκε το όρισμα keyword *flush*."
```

2024-09-11 11:50 UTC, thepetk commented on library/functions.po
> +"ένα αντίγραφο της ιδιότητας με την αντίστοιχη συνάρτηση αξεσουάρ που έχει "
```suggestion
"ένα αντίγραφο της ιδιότητας με την αντίστοιχη συνάρτηση accessor που έχει "
```

2024-09-11 11:50 UTC, thepetk commented on library/functions.po
> +"οριστεί στην διακοσμημένη συνάρτηση.  Αυτό εξηγείται καλύτερα με ένα "
```suggestion
"οριστεί στον decorator.  Αυτό εξηγείται καλύτερα με ένα "
```

2024-09-11 11:50 UTC, thepetk commented on library/functions.po
> +msgstr "Η παράμετρος *start* μπορεί να καθοριστεί ως όρισμα λέξης-κλειδιού."
```suggestion
msgstr "Η παράμετρος *start* μπορεί να καθοριστεί ως όρισμα keyword."
```

2024-09-11 12:35 UTC, skpanagiotis commented
Πρέπει να αλλάξω στο κείμενο, όπου το έχω στιγμιότυπο να το κάνω instance και αν έχω κοντεινερ να γίνει container

2024-09-13 10:26 UTC, thepetk approved these changes
lgtm

2024-10-09 13:10 UTC, merged