Translate tutorial/inputoutput
pygreece/python-docs-gr pull request #554
Opened 2024-09-20 08:31 UTC by skpanagiotis

## Ποιο issue κλείνει το συγκεκριμένο PR;

Closes #60 

## Περιγραφή του PR

Μετάφραση του αρχείου tutorial/inputoutput.po

2024-09-20 10:24 UTC, thepetk requested changes
Νομίζω ο "προσδιοριτστής" είναι καλύτερο να γίνει "αναθέτης" (από την ανάθεση τιμής) και να έχει και το αγγλικό μαζί (secifier).

2024-09-20 10:24 UTC, thepetk commented on tutorial/inputoutput.po
> +msgstr "Φανταχτερή Μορφοποίηση Εξόδου"
```suggestion
msgstr "Ομορφότερη Μορφοποίηση Εξόδου"
```

2024-09-20 10:24 UTC, thepetk commented on tutorial/inputoutput.po
> +"Η μέθοδος :meth:`str.rjust` των αντικειμένων συμβολοσειράς δεξιά-δικαιολογεί "
```suggestion
"Η μέθοδος :meth:`str.rjust` των αντικειμένων συμβολοσειράς τοποθετεί δεξιά "
```

2024-09-20 10:24 UTC, thepetk commented on tutorial/inputoutput.po
> +"Αυτό είναι ιδιαίτερα χρήσιμο σε συνδυασμό με την ενσωματωμένη συνάρτηση :"
```suggestion
"Αυτό είναι ιδιαίτερα χρήσιμο σε συνδυασμό με την ενσωματωμένη (built-in) συνάρτηση :"
```

2024-09-20 10:24 UTC, thepetk commented on tutorial/inputoutput.po
> +"Εάν έχετε μια συμβολοσειρά πολύ μεγάλης μορφής που δεν θέλετε να χωρίσετε, "
```suggestion
"Εάν έχετε μια συμβολοσειρά πολύ μακριάς μορφής που δεν θέλετε να χωρίσετε, "
```

2024-09-20 10:24 UTC, thepetk commented on tutorial/inputoutput.po
> +"Εάν χρησιμοποιούνται ορίσματα λέξεων-κλειδιών στη μέθοδο :meth:`str.format`, "
```suggestion
"Εάν χρησιμοποιούνται keyword ορίσματα στη μέθοδο :meth:`str.format`, "
```

2024-09-20 10:24 UTC, thepetk commented on tutorial/inputoutput.po
> +"Είναι καλή πρακτική να χρησιμοποιείτε τη λέξη-κλειδί :keyword:`with` όταν "
```suggestion
"Είναι καλή πρακτική να χρησιμοποιείτε το keyword :keyword:`with` όταν "
```

2024-09-20 10:24 UTC, thepetk commented on tutorial/inputoutput.po
> +"κλείνει σωστά μετά την ολοκλήρωση της σουίτα του, ακόμα κι αν κάποια στιγμή "
```suggestion
"κλείνει σωστά μετά την ολοκλήρωση της εκτέλεσής του, ακόμα κι αν κάποια στιγμή "
```

2024-09-20 10:24 UTC, thepetk commented on tutorial/inputoutput.po
> +"Εάν δεν χρησιμοποιείτε τη λέξη-κλειδί :keyword:`with`, τότε θα πρέπει να "
```suggestion
"Εάν δεν χρησιμοποιείτε τη keyword :keyword:`with`, τότε θα πρέπει να "
```

2024-09-20 10:24 UTC, thepetk commented on tutorial/inputoutput.po
> +"Η κλήση του ``f.write()`` χωρίς τη χρήση της λέξης-κλειδιού :keyword:`!with` "
```suggestion
"Η κλήση του ``f.write()`` χωρίς τη χρήση της keyword :keyword:`!with` "
```

2024-09-20 10:24 UTC, thepetk commented on tutorial/inputoutput.po
> +"διαβαστεί και θα επιστραφεί, εάν το αρχείο είναι δύο φορές μεγαλύτερο από τη "
Εδώ νομίζω είναι διαφορετικό το νόημα σωστα;

2024-09-20 12:13 UTC, skpanagiotis commented on tutorial/inputoutput.po
> +"διαβαστεί και θα επιστραφεί, εάν το αρχείο είναι δύο φορές μεγαλύτερο από τη "
Το διόρθωσα με το https://github.com/pygreece/python-docs-gr/pull/554/commits/15d902f469dbf5ca703ab6fae99807293f24ddf8

2024-10-09 12:38 UTC, thepetk approved these changes
lgtm

2024-10-09 12:47 UTC, merged