[3.12] Translate tutorial/index.po
pygreece/python-docs-gr pull request #557
Opened 2024-10-23 18:22 UTC by dimpapas

## Ποιο issue κλείνει το συγκεκριμένο PR;

Closes #52

## Περιγραφή του PR

Μετάφραση του `tutorial/index.po` για την Python 3.12

2024-10-24 20:10 UTC, skpanagiotis requested changes
Μια χαρά μπράβο 😊
Έχω βάλει μερικές διορθώσεις. και επίσης τσέκάρε να περνάει τα test. 

Δυστυψώς δεν έχουμε ενημέρώσει ακόμα το Contributing Guide 😢. Αλλά μπορείς να εκτελέσει τοπικά τους ελέγχους με τα βήματα παρακάτω.

Αν δεν το έχεις εγκαταστήσει εκτέλεσε:
`pip install pre-commit`
`pre-commit install`

Και μετά για να εκτελέσεις τα τεστ μπορείς να γράψεις στο terminal στο folder του έργου `pre-commit run --all-files`.

2024-10-24 20:10 UTC, skpanagiotis commented on tutorial/index.po
> +"αυτοτελή, οπότε το σεμινάριο μπορεί να διαβαστεί και εκτός σύνδεσης."
```suggestion
"αυτοτελή, οπότε το tutorial μπορεί να διαβαστεί και εκτός σύνδεσης."
```

2024-10-24 20:10 UTC, skpanagiotis commented on tutorial/index.po
> +"`library-index`. :ref:`reference-index` δίνει έναν πιο επίσημο ορισμό της "
```suggestion
"`library-index`. Το :ref:`reference-index` δίνει έναν πιο επίσημο ορισμό της "
```

2024-10-24 20:10 UTC, skpanagiotis commented on tutorial/index.po
> +"γλώσσας. Για να γράψετε επεκτάσεις σε C ή C++, διαβάστε :ref:`extending-"
```suggestion
"γλώσσας. Για να γράψετε επεκτάσεις σε C ή C++, διαβάστε το :ref:`extending-"
```

2024-10-24 20:10 UTC, skpanagiotis commented on tutorial/index.po
> +"index` και :ref:`c-api-index`. Υπάρχουν επίσης αρκετά βιβλία που καλύπτουν "
```suggestion
"index` και το :ref:`c-api-index`. Υπάρχουν επίσης αρκετά βιβλία που καλύπτουν "
```

2024-10-24 20:10 UTC, skpanagiotis commented on tutorial/index.po
> +"ενότητες και προγράμματα Python, και θα είστε έτοιμοι να μάθετε περισσότερα "
```suggestion
"modules και προγράμματα Python, και θα είστε έτοιμοι να μάθετε περισσότερα "
```

2024-10-24 20:10 UTC, skpanagiotis commented on tutorial/index.po
> +"για τις διάφορες ενότητες βιβλιοθηκών Python που περιγράφονται στο :ref:"
```suggestion
"για τα διάφoρα modules βιβλιοθηκών Python που περιγράφονται στο :ref:"
```

2024-12-04 19:36 UTC, thepetk submitted a review, later dismissed
lgtm!

2024-12-10 20:23 UTC, skpanagiotis approved these changes

2024-12-10 21:35 UTC, thepetk approved these changes
lgtm

2024-12-10 21:35 UTC, merged