Translate file tutorial/classes.po
pygreece/python-docs-gr pull request #558
Opened 2024-10-30 20:07 UTC by AnastasiosLouka

## Ποιο issue κλείνει το συγκεκριμένο PR;

Closes #57

## Περιγραφή του PR

2024-10-31 09:04 UTC, skpanagiotis requested changes
Εξαιρετική δουλειά  Μπράβο.💪

Το μόνο σχόλιο που έχω είναι λίγο προσοχή στα κενά, τίποτε άλλο, που είναι λογικό από κεκτημένη ταχύτητα.

Οι άλλες παρατηρήσεις είναι minor.

2024-10-31 09:04 UTC, skpanagiotis commented on tutorial/classes.po
> +"αντικείμενο της κλάσης είναι μια συνάρτηση χωρίς παραμέτρους που επιστρέφει μια νέα παρουσία της κλάσης."
```suggestion
"αντικείμενο της κλάσης είναι μια συνάρτηση χωρίς παραμέτρους που επιστρέφει μια νέα παρουσία της κλάσης. "
```

2024-10-31 09:04 UTC, skpanagiotis commented on tutorial/classes.po
> +"την δέσμευση *scope_test*\\'s  του *spam*. Η εκχώρηση :keyword:`nonlocal" "
```suggestion
"την δέσμευση *scope_test*\\'s  του *spam*. Η εκχώρηση :keyword:`nonlocal` "
```

2024-10-31 09:04 UTC, skpanagiotis commented on tutorial/classes.po
> +"άλλαξε την δέσμευση του *scope_test*\\'s του *spam* και η εκχώρηση του :keyword:`global`"
```suggestion
"άλλαξε την δέσμευση του *scope_test*\\'s του *spam* και η εκχώρηση του :keyword:`global` "
```

2024-10-31 09:04 UTC, skpanagiotis commented on tutorial/classes.po
> +"ορισμοί συναρτήσεων, αλλά επιτρέπονται άλλες δηλώσεις και μερικές φορές χρήσιμες"
```suggestion
"ορισμοί συναρτήσεων, αλλά επιτρέπονται άλλες δηλώσεις και μερικές φορές χρήσιμες "
```

2024-10-31 09:04 UTC, skpanagiotis commented on tutorial/classes.po
> +"τοπική εμβέλεια --- επομένως, όλες οι εκχωρήσεις σε τοπικές μεταβλητές πηγαίνουν σε αυτόν"
```suggestion
"τοπική εμβέλεια --- επομένως, όλες οι εκχωρήσεις σε τοπικές μεταβλητές πηγαίνουν σε αυτόν "
```

2024-10-31 09:08 UTC, skpanagiotis commented
Επίσης θα μπορούσες να βάλεις τα στοιχεία σου στα metadata 
"Last-Translator: .................................\n"
"Language-Team: PyGreece <pygreece@gmail.com>\n"

2024-11-17 22:39 UTC, gzisopoulos commented on tutorial/classes.po
> +"μέλη του αντικειμένου από τις μεθόδους του: η συνάρτηση της μεθόδου δηλώνεται με "
```suggestion
"μέλη του αντικειμένου από τις μεθόδους του: η μέθοδος δηλώνεται με "
```

2024-11-17 22:43 UTC, gzisopoulos commented on tutorial/classes.po
> +"Αυτό παρέχει σημασιολογία για εισαγωγή και μετονομασία. Σε αντίθεση με την C++ και το"
```suggestion
"Αυτό παρέχει σημασιολογία για εισαγωγή και μετονομασία. Σε αντίθεση με τις γλώσσες C++ και"
```

2024-11-17 22:48 UTC, gzisopoulos commented on tutorial/classes.po
> +"περιστασιακή χρήση όρων Smalltalk και C++. Θα χρησιμοποιούσα όρους Modula-3, "
```suggestion
"περιστασιακή χρήση όρων από τη Smalltalk και τη C++. Θα χρησιμοποιούσα όρους Modula-3, "
```

2024-11-17 22:51 UTC, gzisopoulos commented on tutorial/classes.po
> +"καθώς η αντικειμενοστραφής σημασιολογία του είναι πιο κοντά σε αυτήν της Python από ότι η C++, "
```suggestion
"καθώς η αντικειμενοστραφής σημασιολογία του είναι πιο κοντά σε αυτήν της Python από ότι της C++, "
```

2024-11-17 22:57 UTC, gzisopoulos commented on tutorial/classes.po
> +"συνδεθούν στο ίδιο αντικείμενο. Αυτό είναι γνωστό ως ψευδώνυμο σε άλλες γλώσσες."
Ίσως είναι καλό να κρατήσουμε τον όρο aliasing στα αγγλικά.

2024-11-17 23:05 UTC, gzisopoulos commented on tutorial/classes.po
> +"σημασιολογία του κώδικα της Python που περιλαμβάνει mutable αντικείμενα όπως λίστες, "
Νομίζω το μεταβλητά ταιριάζει λίγο καλύτερα.

2024-11-17 23:36 UTC, gzisopoulos commented on tutorial/classes.po
> +"μπορεί και τα δύο να ορίσουν μια συνάρτηση ``μεγιστοποίηση`` χωρίς σύγχυση --- χρήστες των "
```suggestion
"μπορεί και τα δύο να ορίσουν μια συνάρτηση ``maximize`` χωρίς σύγχυση --- χρήστες των "
```

2024-11-17 23:40 UTC, gzisopoulos commented on tutorial/classes.po
> +"Τα attributes μπορεί να είναι μόνο για ανάγνωση ή εγγράψιμα. Στην τελευταία περίπτωση, είναι δυνατή η εκχώρηση "
```suggestion
"Τα attributes μπορεί να είναι μόνο για ανάγνωση ή εγγράψιμα. Στην τελευταία περίπτωση, είναι δυνατή η ανάθεση "
```

2024-11-18 00:01 UTC, gzisopoulos commented on tutorial/classes.po
>  msgid "The output of the example code is:"
Εδω θέλει να προσθεσουμε τη μεταφραση. "Το αποτέλεσμα του παραδείγματος κώδικα είναι το εξής:"

2024-11-18 00:13 UTC, gzisopoulos commented on tutorial/classes.po
> +"αντικείμενο της κλάσης είναι μια συνάρτηση χωρίς παραμέτρους που επιστρέφει μια νέα παρουσία της κλάσης."
```suggestion
"αντικείμενο της κλάσης είναι μια συνάρτηση χωρίς παραμέτρους που επιστρέφει ένα νέο στιγμιότυπο της κλάσης."
```

2024-11-18 00:28 UTC, gzisopoulos commented on tutorial/classes.po
> +"σε όλες τις περιπτώσεις *Dog*::"
```suggestion
"σε όλα τα στιγμιότυπα *Dog*::"
```

2024-11-18 00:32 UTC, gzisopoulos commented on tutorial/classes.po
> +"Οι πελάτες θα πρέπει να χρησιμοποιούν τα χαρακτηριστικά δεδομένων με προσοχή --- οι πελάτες ενδέχεται να μπερδέψουν"
```suggestion
"Οι χρήστες θα πρέπει να χρησιμοποιούν τα χαρακτηριστικά δεδομένων με προσοχή --- οι πελάτες ενδέχεται να μπερδέψουν"
```

2024-11-18 00:33 UTC, gzisopoulos commented on tutorial/classes.po
> +"Λάβετε υπόψη ότι οι πελάτες μπορούν να προσθέσουν δικά τους χαρακτηριστικά δεδομένων σε ένα αντικείμενο στιγμιότυπου "
```suggestion
"Λάβετε υπόψη ότι οι χρήστες μπορούν να προσθέσουν δικά τους χαρακτηριστικά δεδομένων σε ένα αντικείμενο στιγμιότυπου "
```

2024-11-18 00:36 UTC, gzisopoulos commented on tutorial/classes.po
> +"μεθόδων: δεν υπάρχει καμία πιθανότητα σύγχυσης τοπικών μεταβλητών και των μεταβλητών παραδείγματος"
```suggestion
"μεθόδων: δεν υπάρχει καμία πιθανότητα σύγχυσης των τοπικών μεταβλητών και των μεταβλητών του στιγμιότυπου"
```

2024-11-18 00:40 UTC, gzisopoulos commented on tutorial/classes.po
> +"Νόμιμες χρήσεις της καθολικής εμβέλειας: για ένα πράγμα,οι λειτουργίες και οι λειτουργικές μονάδες "
```suggestion
"νόμιμες χρήσεις της καθολικής εμβέλειας: για ένα πράγμα,οι λειτουργίες και οι λειτουργικές μονάδες "
```

2024-11-18 00:44 UTC, gzisopoulos commented on tutorial/classes.po
> +"χρήσιμο, για παράδειγμα, όταν η βασική κλάση ορίζεται σε άλλη ενότητα::"
```suggestion
"χρήσιμο, για παράδειγμα, όταν η βασική κλάση ορίζεται σε άλλο module::"
```

2024-11-18 00:47 UTC, gzisopoulos commented on tutorial/classes.po
> +"``BaseClassName.methodname(self, arguments)`. Αυτό είναι περιστασιακά χρήσιμο στους πελάτες "
```suggestion
"``BaseClassName.methodname(self, arguments)`. Αυτό είναι περιστασιακά χρήσιμο στους χρήστες "
```

2024-11-18 00:53 UTC, gzisopoulos commented on tutorial/classes.po
> +"από τους περισσότερους κωδικούς Python: ένα όνομα με πρόθεμα κάτω παύλα (π.χ. "
```suggestion
"από τον περισσότερο Python κώδικα: ένα όνομα με πρόθεμα κάτω παύλα (π.χ. "
```

2024-11-18 00:56 UTC, gzisopoulos commented on tutorial/classes.po
> +"κλάση ``Mapping`` και με το ``_MappingSubclass__update`` στο "
```suggestion
"κλάση ``Mapping`` και με το ``_MappingSubclass__update`` στη "
```

2024-11-18 00:57 UTC, gzisopoulos commented on tutorial/classes.po
> +"πρόγραμμα εντοπισμού σφαλμάτων."
```suggestion
"πρόγραμμα εντοπισμού σφαλμάτων(debugger)."
```

2024-11-18 00:59 UTC, gzisopoulos commented on tutorial/classes.po
> +"περιορίζεται στον κώδικα που έχει μεταγλωττιστεί μαζί με byte. Ο ίδιος περιορισμός "
```suggestion
"περιορίζεται στον κώδικα που έχει μεταγλωττιστεί μαζί(byte-compiled). Ο ίδιος περιορισμός "
```

2024-11-18 01:02 UTC, gzisopoulos commented on tutorial/classes.po
> +"αντ' αυτού, και περάστε το ως όρισμα."
```suggestion
"αντ' αυτού, και να το περάστε ως όρισμα."
```

2024-11-18 01:05 UTC, gzisopoulos commented on tutorial/classes.po
> +"Iterators διαπερνά και ενοποιεί την Python. Πίσω από τις σκηνές, η δήλωση :keyword:"
```suggestion
"Iterators διαπερνά και ενοποιεί την Python. Στο παρασκήνιο, η δήλωση :keyword:"
```

2024-11-18 01:07 UTC, gzisopoulos commented on tutorial/classes.po
> +"__next__` η οποία έχει πρόσβαση σε στοιχεία στο κοντέινερ ένα κάθε φορά. Όταν "
```suggestion
"__next__` η οποία έχει πρόσβαση στα στοιχεία του container ένα κάθε φορά. Όταν "
```

2024-11-18 01:07 UTC, gzisopoulos commented on tutorial/classes.po
> +"`for` καλεί :func:`iter` στο αντικείμενο κοντέινερ. Η συνάρτηση "
```suggestion
"`for` καλεί :func:`iter` στο αντικείμενο container. Η συνάρτηση "
```

2024-11-18 01:13 UTC, gzisopoulos commented on tutorial/classes.po
> +"οι generators τερματίζονται, αυξάνουν αυτόματα το :exc:`StopIteration`. "
```suggestion
"οι generators τερματίζονται, εγείρουν αυτόματα την εξαίρεση :exc:`StopIteration`. "
```

2024-11-18 01:14 UTC, gzisopoulos commented on tutorial/classes.po
> +"Ορισμένες απλοί generators μπορούν να κωδικοποιηθούν συνοπτικά ως εκφράσεις χρησιμοποιώντας μια σύνταξη "
```suggestion
"Ορισμένοι απλοί generators μπορούν να γραφτούν συνοπτικά ως εκφράσεις χρησιμοποιώντας μια σύνταξη "
```

2024-11-18 01:15 UTC, gzisopoulos commented on tutorial/classes.po
> +"παρόμοια με τις κατανοήσεις λιστών, αλλά με παρενθέσεις αντί για αγκύλες. "
```suggestion
"παρόμοια με τις list comprehensions, αλλά με παρενθέσεις αντί για αγκύλες. "
```

2024-11-18 01:16 UTC, gzisopoulos commented on tutorial/classes.po
> +"περισσότερο φιλικό προς τη μνήμη από αντίστοιχες κατανοήσεις λιστών."
```suggestion
"περισσότερο φιλικό προς τη μνήμη από αντίστοιχες list comprehensions."
```

2024-11-18 01:22 UTC, gzisopoulos requested changes
Μπραβο!!! Πολυ καλή δουλειά!😃😃
Άφησα και εγώ κάποια suggestions.

2024-12-04 16:50 UTC, thepetk commented on tutorial/classes.po
> +"σημασιολογία του κώδικα της Python που περιλαμβάνει mutable αντικείμενα όπως λίστες, "
Το κάνω commit ως ευμετάβλητο και το βλεπουμε συνολικα στην πορεια αν θελουμε να το αλλαξουμε

2024-12-04 17:46 UTC, thepetk commented on tutorial/classes.po
> +"συνδεθούν στο ίδιο αντικείμενο. Αυτό είναι γνωστό ως ψευδώνυμο σε άλλες γλώσσες."
Ας το δουμε σε δευτερο χρόνο λεω ως μερος ενός συνολικού update για έννοιες που θα πρέπει να μείνουν αμετάφραστες

2024-12-04 18:08 UTC, thepetk reviewed
@skpanagiotis @gzisopoulos έκανα accept τα suggestions και rebase το branch για να δουλεψει και το readthedocs. Feel free to review

2024-12-10 20:42 UTC, skpanagiotis commented on tutorial/classes.po
> +"επανασύνδεση μεταβλητών που βρίσκονται εκτός της ενδότερης εμβέλειας ,μπορεί να χρησιμοποιηθεί η δήλωση του :keyword: "
```suggestion
"επανασύνδεση μεταβλητών που βρίσκονται εκτός της ενδότερης εμβέλειας ,μπορεί να χρησιμοποιηθεί η δήλωση του :keyword:"
```

2024-12-10 20:55 UTC, skpanagiotis commented on tutorial/classes.po
> +"μεταβλητές ζουν στην καθολική εμβέλεια και θα πρέπει να ανακάμψουν εκεί. Η δήλωση `keyword:` "
```suggestion
"μεταβλητές ζουν στην καθολική εμβέλεια και θα πρέπει να ανακάμψουν εκεί. Η δήλωση :keyword:"
```

2024-12-10 21:01 UTC, skpanagiotis approved these changes

2024-12-10 21:36 UTC, thepetk approved these changes
lgtm

2024-12-10 21:56 UTC, gzisopoulos approved these changes

2024-12-10 21:57 UTC, merged