Update Contributing Guide
pygreece/python-docs-gr pull request #561
Opened 2024-11-11 07:40 UTC by skpanagiotis

## Ποιο issue κλείνει το συγκεκριμένο PR;

Closes #548 

## Περιγραφή του PR

Βελτίωση του Contributing Guide για να είναι πιο κατανοητός ο τρόπος που γίνεται συνεισφορά στο έργο της μετάφρασης.

2024-11-11 15:49 UTC, thepetk reviewed
Κάποια μικρά suggestions αφησα μόνο!

2024-11-11 15:49 UTC, thepetk commented on CONTRIBUTING.md
> +1. Για να υποβάλετε μια μετάφραση, πρέπει να έχετε ένα fork του repository, κάνοντας click στο κουμπί fork όπως φαίενται παρακάτω (για περισσότερες πληροφορίες δείτε [εδώ](https://docs.github.com/en/
```suggestion
1. Για να υποβάλετε μια μετάφραση, πρέπει να έχετε ένα fork του repository, κάνοντας click στο κουμπί fork όπως φαίνεται παρακάτω (για περισσότερες πληροφορίες δείτε [εδώ](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo)). Αυτό σας επιτρέπει να δημιουργήσετε ένα προσωπικό αντίγραφο του repository για να δουλέψετε και να κάνετε αλλαγές πάνω σε αυτό:
```

2024-11-11 15:49 UTC, thepetk commented on CONTRIBUTING.md
> +Έχουμε [μια λίστα με issues στο GitHub](https://github.com/pygreece/python-docs-gr/issues?q=is%3Aissue+is%3Aopen+label%3Atranslation) όπου συντονίζουμε τη δουλειά που γίνεται ή που πρέπει να γίνει ώσ
```suggestion
Έχουμε [μια λίστα με issues στο GitHub](https://github.com/pygreece/python-docs-gr/issues?q=is%3Aissue+is%3Aopen+label%3Atranslation) όπου συντονίζουμε τη δουλειά που γίνεται ή που πρέπει να γίνει ώστε να γίνεται διαχωρισμός αρμοδιοτήτων και διαχείριση της δουλειάς και των απαιτούμενων ενεργειών.
```

2024-11-11 15:49 UTC, thepetk commented on CONTRIBUTING.md
> +-   Αφήστε ένα σχόλιο στο **Issue** λέγοντας ότι θέλετε να συνεισφέρετε, αναλαμβάνοντας το συγκεκριμένο **Issue**.
Θα μπορούσαμε να βάλουμε κάποιο λινκ απο αντίστοιχο σχόλιο ως παράδειγμα εδω.

2024-11-11 15:49 UTC, thepetk commented on CONTRIBUTING.md
> +To milestone που μπορείτε να συνεισφέρετε είναι το `translate_3.12_additional`. Άμα είναι η πρώτη σας φορά σε αυτό το έργο ή γενικότερα σε έργο ανοιχτού λογισμικού είναι προτιμότερο να αναλάβετε ένα
Ανοιχτού κώδικα έχω την εντύπωση είναι ο όρος στα ελληνικά.
```suggestion
To milestone που μπορείτε να συνεισφέρετε είναι το `translate_3.12_additional`. Άμα είναι η πρώτη σας φορά σε αυτό το έργο ή γενικότερα σε έργο ανοιχτού κώδικα είναι προτιμότερο να αναλάβετε ένα **Issue** με **label** _good first issue_.
```

2024-11-14 14:59 UTC, vadal commented on CONTRIBUTING.md
> +-   Αν από τη συζήτηση προκύψει ότι απαιτείται κάποια αλλάγη, είναι αρρεστό να την αναλάβετε εσείς. Κατ' αυτόν τον τρόπο θα κλείσετε το **Issue** σας με ένα δικό σας PR.
Υπάρχει ένα ορθογραφικό λάθος στην πρώτη πρόταση: αρρεστό -> αρεστό

2024-11-14 14:59 UTC, vadal commented on CONTRIBUTING.md
> +Τα αρχεία που πρέπει να μεταφρστούν είναι αυτά με την κατάληξη `.po`.
Λείπει ένα γράμμα από το **μεταφραστούν**

2024-11-14 14:59 UTC, vadal commented on CONTRIBUTING.md
> +4.  Αφού έχετε διαλέξει το αρχείο σας, ξεκινήστε την μετάφραση στο IDE της επιλογής σας. Επίσης μπορείτε να χρησιμοποιείσετε εργαλεία για την σωστή μετάφραση προτάσεων, φράσεων ή λέξεων.
Ορθογραφικό λάθος: χρησιμοποιείσετε -> χρησιμοποιήσετε

2024-11-14 14:59 UTC, vadal commented on CONTRIBUTING.md
> +Μπράβο σας! Ανεβάσετε το πρώτο σας PR. Τώρα απλώς περιμένετε να το αξιολογήσουν οι διαχειριστές, και έχετε το νου σας, μπορεί να σας ζητήσουν κάποιες αλλαγές.
Πιθανώς να αφαιρούσα το _σας_ μετά το _Μπράβο_ για να ακούγεται πιο native. Επίσης, υπάρχει ένα λάθος στον χρόνο του ρήματος στην αρχή της πρότασης:  Ανεβάσετε -> Ανεβάσατε

2024-11-14 14:59 UTC, vadal commented on CONTRIBUTING.md
> +-   Τα επίσημα έγγραφα της Python είναι άπειρα! Όποια εμπόδια βρείτε μπορείτε πάντα να επισημάνετε το κείμενο ως "ασαφές" ή να το αναθεωρήσετε στο μέλλον. Μην σπαταλάτε ώρες αναζητώντας την τέλεια λέ
Το _Όποια εμπόδια βρείτε_ θα μπορούσε να αντικατασταθεί με κάτι τέτοιο: Αν αντιμετωπίσετε εμπόδια,

2024-11-14 14:59 UTC, vadal commented on CONTRIBUTING.md
> +-   Μπορείτε να διαβάσετε τις Συχνές Ερωτήσεις για να διαβάσετε για γνωστά ζητήματα.
Το πρώτο _διαβάσετε_ θα μπορούσε να γίνει _συμβουλευτείτε_ για να μη χρησιμοποιείτε δύο φορές.

2024-11-18 14:27 UTC, thepetk approved these changes, later dismissed
lgtm

2024-11-18 15:53 UTC, gzisopoulos commented
Οταν κάνει κάποιος fork ενα repository αυτο εχει προεπιλεγμενο να κάνει copy μονο το main branch.  Αν ακολουθησει καποιος τα βηματα με το main branch τοτε όταν κανει `pip install -r requirements.txt` θα πάρει error γιατι το cpython directory ειναι κενο. Οποτε ισως πρέπει να τους γράψουμε να κανουν fetch πρωτα και checkout στο 3.12 πριν κανουν install τα requirements ή να ξεκλικαρουν το μονο το main branch οταν κανουν fork και να χρειαζονται μονο ενα checkout πριν γινουν install τα requirements.
![image](https://github.com/user-attachments/assets/8c69e274-8c20-4dd7-80e4-2c7af4413fee)

2024-11-19 10:32 UTC, skpanagiotis commented
Σωστή αυτή η παρατήρηση @gzisopoulos . Για αυτό πρέπει να γίνει default branch μας το 3.12 αφού γίνει merge με το master.

2024-11-19 18:54 UTC, gzisopoulos commented
> Σωστή αυτή η παρατήρηση @gzisopoulos . Για αυτό πρέπει να γίνει default branch μας το 3.12 αφού γίνει merge με το master.

Θα

2024-11-19 23:59 UTC, gmargaritis requested changes
Πολύ καλές αλλαγές! Kudos to everyone 🎉

2024-11-19 23:59 UTC, gmargaritis commented on CONTRIBUTING.md
> +        python scripts/check_spelling.py <dir>/<file>.po
```suggestion
        python scripts/check_spelling.py <φάκελος>/<όνομα_του_αρχείου>.po
```

2024-11-19 23:59 UTC, gmargaritis commented on CONTRIBUTING.md
> +        powrap <φακελος>/<ονομα_του_αρχειου>.po
```suggestion
        powrap <φάκελος>/<όνομα_του_αρχείου>.po
```

2024-11-19 23:59 UTC, gmargaritis commented on CONTRIBUTING.md
> +![pr_descrtiption](/public/assets/pr-descrtiption.png)
```suggestion
![pr_descrtiption](/public/assets/pr-description.png)
```

2024-11-19 23:59 UTC, gmargaritis commented on CONTRIBUTING.md
> +<h2 id="preparation">Προετοιμασία</h2>
Θα πρότεινα να συνεχίσουμε με md format

```suggestion
### Προετοιμασία
```

2024-11-19 23:59 UTC, gmargaritis commented on CONTRIBUTING.md
> +<h2 id="contributing">Συνεισφορά</h2>
```suggestion
## Συνεισφορά
```

2024-11-19 23:59 UTC, gmargaritis commented on CONTRIBUTING.md
> +<h3 id="file-translation">Μετάφραση Αρχείου</h3>
```suggestion
### Μετάφραση Αρχείου
```

2024-11-19 23:59 UTC, gmargaritis commented on CONTRIBUTING.md
> +<h3 id="translation-review">Αξιολόγηση Μετάφρασης</h3>
```suggestion
### Αξιολόγηση Μετάφρασης
```

2024-11-19 23:59 UTC, gmargaritis commented on CONTRIBUTING.md
> +<h2 id="start-translation">Λερώστε τα χέρια σας! Μεταφράστε!</h2>
```suggestion
## Λερώστε τα χέρια σας! Μεταφράστε!
```

2024-11-19 23:59 UTC, gmargaritis commented on CONTRIBUTING.md
> +To milestone που μπορείτε να συνεισφέρετε είναι το `translate_3.12_additional`. Άμα είναι η πρώτη σας φορά σε αυτό το έργο ή γενικότερα σε έργο ανοιχτού κώδικα είναι προτιμότερο να αναλάβετε ένα **Is
```suggestion
To milestone που μπορείτε να συνεισφέρετε είναι το [translate_3.12_additional](https://github.com/pygreece/python-docs-gr/milestone/3). Άμα είναι η πρώτη σας φορά σε αυτό το έργο ή γενικότερα σε έργο ανοιχτού κώδικα είναι προτιμότερο να αναλάβετε ένα **Issue** με **label** [_good first issue_](https://github.com/pygreece/python-docs-gr/labels/good%20first%20issue).
```

2024-11-19 23:59 UTC, gmargaritis commented on CONTRIBUTING.md
> +-   `god` (για τους τολμηρούς) για αρχεία με περισσόρερες από _2500_ γραμμές
```suggestion
-   [small](https://github.com/pygreece/python-docs-gr/labels/small) για αρχεία με λιγότερες από _200_ γραμμές
-   [medium](https://github.com/pygreece/python-docs-gr/labels/medium) για αρχεία με λιγότερες από _500_ γραμμές
-   [large](https://github.com/pygreece/python-docs-gr/labels/large) για αρχεία με λιγότερες από _1000_ γραμμές
-   [xlarge](https://github.com/pygreece/python-docs-gr/labels/xlarge) για αρχεία με λιγότερες από _2500_ γραμμές
-   [god](https://github.com/pygreece/python-docs-gr/labels/small) (για τους τολμηρούς) για αρχεία με περισσόρερες από _2500_ γραμμές
```

2024-11-20 07:40 UTC, skpanagiotis commented on CONTRIBUTING.md
> +<h2 id="preparation">Προετοιμασία</h2>
Το έγραψα έτσι για να υπάρχει Connection μεταξύ των header και των περιεχομένων.

2024-11-20 08:25 UTC, gmargaritis commented on CONTRIBUTING.md
> +<h2 id="preparation">Προετοιμασία</h2>
Έχουμε τη δυνατότητα να κάνουμε link σε headers μέσα στο αρχείο χρησιμοποιώντας το παρακάτω format[^1]:

```
[this is a link](#this-is-a-header)
```

Πιστεύω είναι καλύτερο να κρατάμε το format σε md όσο περισσότερο γίνεται!

[^1]: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#section-links

2024-11-20 09:01 UTC, gmargaritis submitted a review, later dismissed
LGTM 🚀

2024-11-20 10:13 UTC, lysnikolaou reviewed
@skpanagiotis and everyone, amazing work! Thanks a lot for doing this!

A couple of comments (here and inline):

Can we add a second command to the 4th step of setting up. After `git remote add upstream`, it'd be best if contributors also did `git remote set-url --push upstream git@github.com:<your-username>/cpython.git` to avoid accidentally pushing to the upstream repo.

2024-11-20 10:13 UTC, lysnikolaou commented on CONTRIBUTING.md
> +Εφόσον σας έχει ανατεθεί ένα αρχείο προς μετάφραση, ήρθε η ώρα να λερώσετε τα χέρια σας και να Ξεκινήσετε!
```suggestion
Εφόσον σας έχει ανατεθεί ένα αρχείο προς μετάφραση, ήρθε η ώρα να λερώσετε τα χέρια σας και να ξεκινήσετε!
```

2024-11-20 10:13 UTC, lysnikolaou commented on CONTRIBUTING.md
> +Τα εργαλεία που προτείνουμε για να χρησιμοποιήσετε είναι το [VScode](https://code.visualstudio.com/) ή το [PoEdit](https://poedit.net/). Για το [VScode](https://code.visualstudio.com/) μια χρήσιμη επ
```suggestion
Τα εργαλεία που προτείνουμε να χρησιμοποιήσετε είναι το [VScode](https://code.visualstudio.com/) ή το [PoEdit](https://poedit.net/). Για το [VScode](https://code.visualstudio.com/) μια χρήσιμη επέκταση είναι το [`gettext` extension](https://marketplace.visualstudio.com/items?itemName=mrorz.language-gettext). Αντίθετα το [PoEdit](https://poedit.net/) χρησιμοποιεί ένα καλύτερο περιβάλλον διεπαφής και δεν απατείται να ασχοληθεί ο χρήστης με τη δομή του αρχείου.
```

2024-11-20 10:13 UTC, lysnikolaou commented on CONTRIBUTING.md
> +8. Έπειτα μπορείτε να ανοίξετε ένα Pull Request προκειμένου να εξεταστεί/ελεγχθεί η συνεισφορά σας, να γίνουν κάποια σχόλια και εν τέλη να προσαρτηθεί στο βασικό repository. Εφόσον έχετε κάνει push τ
```suggestion
8. Έπειτα μπορείτε να ανοίξετε ένα Pull Request προκειμένου να εξεταστεί/ελεγχθεί η συνεισφορά σας, να γίνουν κάποια σχόλια και εν τέλει να προσαρτηθεί στο βασικό repository. Εφόσον έχετε κάνει push το branch σας θα δείτε κάτι όπως παρακάτω:
```

2024-11-20 10:13 UTC, lysnikolaou commented on CONTRIBUTING.md
> +Μπράβο! Ανεβάσατε το πρώτο σας PR. Τώρα απλώς περιμένετε να το αξιολογήσουν οι διαχειριστές, και έχετε το νου σας, μπορεί να σας ζητήσουν κάποιες αλλαγές.
```suggestion
Μπράβο! Ανεβάσατε το πρώτο σας PR. Τώρα απλώς περιμένετε να το αξιολογήσουν οι διαχειριστές, και έχετε στο νου σας ότι μπορεί να σας ζητήσουν κάποιες αλλαγές.
```

2024-11-20 15:23 UTC, skpanagiotis commented
Πρόσθεσα και το extra βήμα του @lysnikolaou

2024-11-20 20:59 UTC, lysnikolaou reviewed
LGTM! Thanks everyone!

2024-11-20 20:59 UTC, lysnikolaou commented on CONTRIBUTING.md
> +5. Και πληκτρολογήστε την παρακάτω εντολή για το submodule του repository σας:
```suggestion
5. Και πληκτρολογήστε την παρακάτω εντολή για το upstream του repository σας:
```

2024-11-20 21:00 UTC, lysnikolaou commented
Pushed the nitty comment I made above, I think we're good to merge at this point.

2024-11-21 07:56 UTC, lysnikolaou reviewed
Approving so that the button turns green.

2024-11-21 07:56 UTC, lysnikolaou approved these changes
Approving so that the button turns green.

2024-11-21 08:00 UTC, gzisopoulos approved these changes

2024-11-21 08:01 UTC, merged