Translate file reference/grammar.po
pygreece/python-docs-gr pull request #567
Opened 2024-12-04 22:27 UTC by prokoposgiannis

## Ποιο issue κλείνει το συγκεκριμένο PR;

Closes #510 

## Περιγραφή του PR

Μία πολύ απλή μετάφραση για το reference/grammar.po. Μεταφράστηκαν 3 σημεία, και για το 3ο, η λέξη που χρησιμοποιήθηκε για την αγγλική "lookahead" είναι η "προσβλεψιμότητα" που σημαίνει "αυτό που προσβλέπεται, που το αναμένεται". Πάρθηκε από το chat GPT μια και δεν έβρισκα κάτι καλύτερο και περιμένω προτάσεις για κάτι πιο κατανοητό.

2024-12-05 22:23 UTC, skpanagiotis requested changes
Μπράβο 🎯καλη δουλειά. Έκανα μερικές προτάσεις, και αναφορικά με το lookahead αυτό που βρήκα και νομίζω ότι κολλάει καλύτερα είναι η λέξη `προεπισκόπηση`.

2024-12-05 22:23 UTC, skpanagiotis commented on reference/grammar.po
> +"προσβλεψιμότητα (δηλαδή, είναι απαραίτητο να ταιριάζει, αλλά δεν "
```suggestion
"προεπισκόπηση (δηλαδή, είναι απαραίτητο να ταιριάζει, αλλά δεν "
```

2024-12-06 08:19 UTC, skpanagiotis commented
Επιπλέον πρέπει να προστεθεί η λέξη `token` στο λεξικό μας, `dictionaries\main.txt`, καθώς σκάει στο pospell.

2024-12-06 08:26 UTC, skpanagiotis requested changes

2024-12-06 08:26 UTC, skpanagiotis commented on reference/grammar.po
> +"PO-Revision-Date: 2024-12-03 21:40+2\n"
Εδώ πέρα δεν είναι σε σωστό forma η ημερομηνία,
Χρειάζεται κάτι τέτοιο, που λέει και το timezone σου:
`2024-09-07 18:18+0300\n`

2024-12-09 08:04 UTC, skpanagiotis commented
Επίσης @prokoposgiannis  μην ξεχάσεις να προσθέσεις το όνομα σου στο αρχείο με τους [TRANSLATORS](https://github.com/pygreece/python-docs-gr/blob/3.12/TRANSLATORS)

2024-12-09 08:06 UTC, prokoposgiannis commented
Έγινε @skpanagiotis ! Θα το προχωρήσω σήμερα :D

2025-02-09 20:08 UTC, skpanagiotis commented
Για να κάνουμε Unfreeze αυτό το PR, (το έχουμε ξεχάσει) λείπει η λεξη `token`, από το λεξικό, και επίσης κάνε και ένα merge να έχει latest εικόνα με το parent repo.

2025-04-09 06:20 UTC, skpanagiotis commented
Close due to the completion with #599

2025-04-09 06:20 UTC, closed without merging