Translate file reference/introduction.po  (and additions in dictionary)
pygreece/python-docs-gr pull request #570
Opened 2024-12-09 10:45 UTC by steliosrotas

## Ποιο issue κλείνει το συγκεκριμένο PR;

Closes #512 

## Περιγραφή του PR

I translated the file reference/introduction.po and added words in dictionary so that pospell works.

2024-12-09 11:19 UTC, lysnikolaou reviewed
Thanks @steliosrotas! Πολύ καλή δουλειά. 🚀 Άφησα μερικά comments για κάποιες διορθώσεις.

2024-12-09 11:19 UTC, lysnikolaou commented on reference/introduction.po
> +"του κώδικα της Python απευθείας στις μονλαδες του .NET. Δημιουργήθηκε από "
```suggestion
"του κώδικα της Python απευθείας στην γλώσσα assembly του .NET. Δημιουργήθηκε από "
```

2024-12-09 11:19 UTC, lysnikolaou commented on reference/introduction.po
> +"τον *Jim Hugunin*, ο πρωτότυπος δημιουργός της Jython. Για περισσότερες "
```suggestion
"τον Jim Hugunin, τον πρωτότυπο δημιουργό της Jython. Για περισσότερες "
```

2024-12-09 11:19 UTC, lysnikolaou commented on reference/introduction.po
> +"υποστήριξη για *stackless* και τον μεταγλωττιστή *Just in Time*. Ένας από "
Νομίζω θα ήταν καλύτερο να κρατάμε consistent το formatting μεταξύ του original και του translation.

```suggestion
"υποστήριξη για stackless και τον μεταγλωττιστή Just in Time. Ένας από "
```

2024-12-09 11:19 UTC, lysnikolaou commented on reference/introduction.po
> +"αυτόν τον συμβολισμό. Ένας αστερίσκος (``*``) σημαίνει μηδέν ή περισσότερες "
Νομίζω εδώ το καλύτερο είναι να εξηγήσουμε περιφραστικά τι σημαίνει least binding, most binding etc.

Το ίδιο ισχύει και για όπου αναφέρεται η συγκεκριμένη φράση σε αυτή την παράγραφο.

```suggestion
"διαχωρίσει τις εναλλακτικές· έχει την μικρότερη προτεραιότητα στην σειρά προτεραιότητας "
"πράξεων αυτού του συμβολισμού. Ένας αστερίσκος (``*``) σημαίνει μηδέν ή περισσότερες "
```

2024-12-09 11:19 UTC, lysnikolaou commented on reference/introduction.po
> +"παρενθέσεις. Οι συμβολοσειρές είναι περιφραγμένες από εισαγωγικά. Οι κενοί "
```suggestion
"όσο το δυνατόν πιο σφιχτά· οι παρενθέσεις χρησιμοποιούνται για "
"ομαδοποίηση. Οι συμβολοσειρές είναι περιφραγμένες από εισαγωγικά. Οι κενοί "
```

2024-12-09 11:19 UTC, lysnikolaou commented on reference/introduction.po
> +"κάθετη μπάρα."
```suggestion
"μπορεί να έχουν εναλλακτική μορφή με κάθε γραμμή μετά την πρώτη να ξεκινάει με την "
"κάθετη μπάρα."
```

2024-12-09 11:19 UTC, lysnikolaou commented on reference/introduction.po
> +"(συμπεριλαμβανομένου) εύρος *ASCII* χαρακτήρων. Η φράση ανάμεσα σε αγκύλες "
```suggestion
"(κλειστό) διάστημα *ASCII* χαρακτήρων. Η φράση ανάμεσα σε γωνιακές παρενθέσεις "
```

2024-12-09 11:19 UTC, lysnikolaou commented on reference/introduction.po
> +"Μολονότι η ιδέα που χρησιμοποιείται είναι σχεδόν το ίδιο, υπάρχει μεγάλη "
```suggestion
"Μολονότι η σημειογραφία που χρησιμοποιείται είναι σχεδόν η ίδια, υπάρχει μεγάλη "
```

2024-12-09 11:19 UTC, lysnikolaou commented on reference/introduction.po
> +msgstr "συμβολισμός"
Μήπως να μεταφράσουμε το notation ως σημειογραφία; Μου ακούγεται πιο σωστό. 🤔 

```suggestion
msgstr "συμβολισμός"
```

2024-12-09 14:44 UTC, skpanagiotis commented
@lysnikolaou υπάρχει και το #565 που είναι το ίδιο αρχείο. Οπότε να κρατήσουμε τελικά ένα από τα δύο, λογικά το παρόν;!.

2024-12-09 15:23 UTC, lysnikolaou commented
Σωστό! Έκλεισα το #565, ας αφήσουμε αυτό ανοιχτό.

2024-12-12 21:07 UTC, skpanagiotis requested changes
Κάτι διπλά κενά βρήκα, και ένα σημείο που θέλει άλλη μετάφραση η λέξης `Notation`.

2024-12-12 21:07 UTC, skpanagiotis commented on reference/introduction.po
> +msgstr "Συμβολισμός"
```suggestion
msgstr "Σημειογραφία"
```

2024-12-12 21:07 UTC, skpanagiotis commented on reference/introduction.po
> +"τροποποιημένο  γραμματικό συμβολισμό στην  `μορφή Μπάκους-Νάουρ (BNF) "
```suggestion
"τροποποιημένο  γραμματικό συμβολισμό στην `μορφή Μπάκους-Νάουρ (BNF) "
```

2024-12-12 21:07 UTC, skpanagiotis commented on reference/introduction.po
> +"επόμενο κεφάλαιο  (\"Λεξιλογική Ανάλυση\") είναι λεξιλογικοί ορισμοί· οι "
```suggestion
"επόμενο κεφάλαιο (\"Λεξιλογική Ανάλυση\") είναι λεξιλογικοί ορισμοί· οι "
```

2024-12-13 10:06 UTC, skpanagiotis approved these changes

2024-12-13 14:19 UTC, thepetk approved these changes
Πολύ καλή δουλειά!! 🎉🎉🎉

2024-12-13 14:32 UTC, lysnikolaou approved these changes
LGTM! Thanks @steliosrotas! 🚀

2024-12-13 14:33 UTC, merged