Translate/reference executionmodel
pygreece/python-docs-gr pull request #573
Opened 2024-12-09 16:53 UTC by mgiannopoulos24

## Ποιο issue κλείνει το συγκεκριμένο PR;

Closes #509

## Περιγραφή του PR

Προστέθηκε η μετάφραση του `executionmodel.po`.

## Λίστα εργασιών

- [Χ] Προσθήκη λέξεων στο ευρετήριο `main.txt`.

2024-12-09 19:46 UTC, mgiannopoulos24 commented
Νομίζω το πρόβλημα είναι ότι τα έχω βάλει όπως ήταν. Δεν ξέρω τι άλλο μπορεί να ευθύνεται.

```css
[':keyword:`with`', ':keyword:`except`', ':keyword:`except* <except_star>`']
```

2024-12-09 21:59 UTC, mgiannopoulos24 commented
Είναι σωστό απλά επειδή κόβεται το οποιοδήποτε κομμάτι που είναι σε backticks κάνει fail το readthedocs.

2024-12-10 09:04 UTC, lysnikolaou commented on reference/executionmodel.po
> +"keyword:`yield`, ``yield from``, :keyword:`await` ή :token:`:=<python-"
Νομίζω το πρόβλημα είναι η έλλειψη κενού ανάμεσα στην λέξη "εκφράσεις" και στην άνω-κάτω τελεία `:`.

```suggestion
"Οι εκφράσεις σε πεδία σημειώσεων δεν μπορούν να περιέχουν τις εκφράσεις "
":keyword:`yield`, ``yield from``, :keyword:`await` ή :token:`:=<python-"
```

2024-12-10 10:37 UTC, mgiannopoulos24 commented
Ας ελπίσουμε να δουλέψει.

2024-12-10 10:52 UTC, mgiannopoulos24 commented
To powrap το πάει από πάνω. Δεν με αφήνει να το αλλάξω.

2024-12-10 11:06 UTC, lysnikolaou commented on reference/executionmodel.po
> +"`type`αξιολογούνται *καθυστερημένα*. Το ίδιο ισχύει και για τα όρια και τους "
Το προηγούμενο λάθος φτιάχτηκε. Τώρα το readthedocs παραπονιέται για εδώ.


```suggestion
"`type` αξιολογούνται *καθυστερημένα*. Το ίδιο ισχύει και για τα όρια και τους "
```

2024-12-10 15:07 UTC, lysnikolaou commented on reference/executionmodel.po
> +"``__main__``, το ``__builtins__`` είναι το ενσωματωμένο module :mod:"
Νομίζω το επόμενο error έχει να κάνει με αυτό εδώ.

```suggestion
"`__main__`, το ``__builtins__`` είναι το ενσωματωμένο module :mod:"
```

2024-12-10 19:10 UTC, mgiannopoulos24 commented
Απίστευτο.. Δούλεψε!

2024-12-10 22:42 UTC, skpanagiotis requested changes
Μπράβο πολύ καλή δουλειά στη μετάφραση 💪 Αποτελεί δύσκολο κείμενο από πλευράς κατανόηση, μια παρατήρηση μου είναι είναι οι προσθήκες πολλών λέξεων στο main.txt. Λογικά έτρεξες το script από το #574. Έχει βάλει πολλές λέξεις όπως επίσης και λέξεις που δεν πρέπει να μπούν (π.χ. ανορθόγραφες ή χωρίς σημεία στίξης). Σκοπός του main.txt είναι να μπούν λέξεις αγγλικές καθώς και ελληνικές που είναι λογικό να μην υπάρχουν στο λεξικό. Γνώμη μου είναι να γίνουν revert οι αλλαγές στο main.txt.

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"ένα κομμάτι κειμένου προγράμματος Python που εκτελείται ως μονάδα. Τα "
```suggestion
"ένα κομμάτι κειμένου προγράμματος Python που εκτελείται ως μια μονάδα. Τα "
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"μπλοκ κώδικα. Μια εντολή σεναρίου (μια εντολή που καθορίζεται στο διερμηνέα "
```suggestion
"μπλοκ κώδικα. Μια script εντολή (μια εντολή που καθορίζεται στο διερμηνέα "
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"εκτελείται ως σενάριο ανώτερου επιπέδου (ως ενότητα ``__main__``) από τη "
```suggestion
"εκτελείται ως ανωτέρου επιπέδου script (ως module ``__main__``) από τη "
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"περιέχει ορισμένες διοικητικές πληροφορίες (που χρησιμοποιούνται για "
```suggestion
"περιέχει ορισμένες πληροφορίες διαχείρισης (που χρησιμοποιούνται για "
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +msgstr "Ονομασία και δέσμευση"
```suggestion
msgstr "Ονομασία και σύνδεση"
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +msgstr "Δέσμευση ονομάτων"
```suggestion
msgstr "Σύνδεση ονομάτων"
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +":dfn:`Ονόματα` αναφέρονται σε αντικείμενα. Τα ονόματα εισάγονται μέσω "
```suggestion
":dfn:`Names` αναφέρονται σε αντικείμενα. Τα ονόματα εισάγονται μέσω "
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +":ref:`στόχοι <assignment>` που είναι αναγνωριστικά αν εμφανίζονται σε μια "
```suggestion
":ref:`targets <assignment>` που είναι αναγνωριστικά αν εμφανίζονται σε μια "
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"δομική αντιστοίχηση μοτίβων,"
```suggestion
"δομική αντιστοίχησης μοτίβων,"
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +msgstr "σε ένα capture pattern κατά τη δομική αντιστοίχηση μοτίβων"
```suggestion
msgstr "σε ένα στιγμιότυπο μοτίβου κατά τη δομική αντιστοίχησης μοτίβων"
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"Η δήλωση :keyword:`!import` της μορφής ``from ... import *`` δεσμεύει όλα τα "
```suggestion
"Η δήλωση :keyword:`!import` της μορφής ``from ... import *`` συνδέει όλα τα "
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"αποδεσμεύσει το όνομα)."
```suggestion
"αποσυνδέσει το όνομα)."
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"είναι μια :dfn:`ελεύθερη μεταβλητή`."
```suggestion
"είναι μια :dfn:`free variable`."
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"`δέσμευση` αυτού του ονόματος που καθορίζεται από τους παρακάτω κανόνες "
```suggestion
"`binding` αυτού του ονόματος που καθορίζεται από τους παρακάτω κανόνες "
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"Ένα :dfn:`πεδίο` ορίζει την ορατότητα ενός ονόματος μέσα σε ένα μπλοκ. Αν "
```suggestion
"Ένα :dfn:`scope` ορίζει την ορατότητα ενός ονόματος μέσα σε ένα μπλοκ. Αν "
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"εκτός αν ένα περιεχόμενο μπλοκ εισάγει διαφορετική δέσμευση για το όνομα."
```suggestion
"εκτός αν ένα περιεχόμενο μπλοκ εισάγει διαφορετική σύνδεση για το όνομα."
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"που είναι ορατά σε ένα μπλοκ κώδικα ονομάζεται :dfn:`περιβάλλον` του μπλοκ."
```suggestion
"που είναι ορατά σε ένα μπλοκ κώδικα ονομάζεται :dfn:`environment` του μπλοκ."
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"Όταν ένα όνομα δεν βρίσκεται καθόλου, εγείρεται μια εξαίρεση :exc:"
```suggestion
"Όταν ένα όνομα δεν βρίσκεται καθόλου, γίνεται raise μια εξαίρεση :exc:"
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"τιμή στο σημείο που χρησιμοποιείται το όνομα, εγείρεται μια εξαίρεση :exc:"
```suggestion
"τιμή στο σημείο που χρησιμοποιείται το όνομα, γίνεται raise μια εξαίρεση :exc:"
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"Αν μια λειτουργία δέσμευσης ονομάτων συμβεί οπουδήποτε μέσα σε ένα μπλοκ "
```suggestion
"Αν μια λειτουργία σύνδεσης ονομάτων συμβεί οπουδήποτε μέσα σε ένα μπλοκ "
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"δέσμευσης ονομάτων να συμβαίνουν οπουδήποτε μέσα σε ένα μπλοκ κώδικα. Οι "
```suggestion
"σύνδεση ονομάτων να συμβαίνουν οπουδήποτε μέσα σε ένα μπλοκ κώδικα. Οι "
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"ολόκληρο το κείμενο του μπλοκ για λειτουργίες δέσμευσης ονομάτων. Δείτε :ref:"
```suggestion
"ολόκληρο το κείμενο του μπλοκ για λειτουργίες σύνδεσης ονομάτων. Δείτε :ref:"
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"των ονομάτων που καθορίζονται στη δήλωση αναφέρονται στις δεσμεύσεις αυτών "
```suggestion
"των ονομάτων που καθορίζονται στη δήλωση αναφέρονται στις συνδέσεις αυτών "
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"Η δήλωση :keyword:`global` έχει το ίδιο πεδίο με μια λειτουργία δέσμευσης "
```suggestion
"Η δήλωση :keyword:`global` έχει το ίδιο πεδίο με μια λειτουργία σύνδεσης "
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"module εισάγεται Το κύριο module για ένα σενάριο ονομάζεται πάντα :mod:"
```suggestion
"module εισάγεται Το κύριο module για ένα script ονομάζεται πάντα :mod:"
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"scopes>`, expressions, but it does not include :ref:`annotation scopes "
```suggestion
"expressions, but it does not include :ref:`annotation scopes <annotation-"
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"<annotation-which have access to their enclosing class scopes. This means "
```suggestion
"scopes>`, which have access to their enclosing class scopes. This means that "
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"that the following will fail::"
```suggestion
"the following will fail::"
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"εκφράσεις γεννητριών, αλλά δεν περιλαμβάνει:ref:`πεδία σημειώσεων "
```suggestion
"εκφράσεις γεννητριών, αλλά δεν περιλαμβάνει :ref:`πεδία σημειώσεων "
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +msgstr "Πεδία σημειώσεων"
```suggestion
msgstr "Σημειογραφία πεδία"
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"`type` εισάγουν *πεδία σημειώσεων*, τα οποία συμπεριφέρονται κυρίως όπως τα "
```suggestion
"`type` εισάγουν *πεδία σημειογραφίας*, τα οποία συμπεριφέρονται κυρίως όπως τα "
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"πεδία συναρτήσεων,αλλά με κάποιες εξαιρέσεις που συζητούνται παρακάτω. :term:"
```suggestion
"πεδία συναρτήσεων, αλλά με κάποιες εξαιρέσεις που συζητούνται παρακάτω. :term:"
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"`Οι σημειώσεις <annotation>` προς το παρόν δεν χρησιμοποιούν πεδία "
```suggestion
"`Annotations <annotation>` προς το παρόν δεν χρησιμοποιούν πεδία "
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +msgstr "Τα πεδία σημειώσεων χρησιμοποιούνται στα παρακάτω συμφραζόμενα:"
```suggestion
msgstr "Τα πεδία σημειογραφίας χρησιμοποιούνται στα παρακάτω συμφραζόμενα:"
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"Λίστες παραμέτρων τύπου για :ref:`γενικούς τύπους ψευδωνύμων <generic-type-"
```suggestion
"Λίστες παραμέτρων τύπου για :ref:`generic type aliases  <generic-type-"
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"Λίστες παραμέτρων τύπου για :ref:`γενικές συναρτήσεις <generic-functions>`. "
```suggestion
"Λίστες τύπου παραμέτρου για :ref:`generic functions <generic-functions>`. "
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"Οι σημειώσεις μιας γενικής συνάρτησης εκτελούνται μέσα στο πεδίο σημειώσεων, "
```suggestion
"Οι σημειογραφίες μιας γενικής συνάρτησης εκτελούνται μέσα στο πεδίο σημειώσεων, "
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"Λίστες παραμέτρων τύπου για :ref:`γενικές κλάσεις <generic-classes>`. Οι "
```suggestion
"Λίστες παραμέτρων τύπου για :ref:`generic classes <generic-classes>`. Οι "
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"Τα όρια και οι περιορισμοί για μεταβλητές τύπου (:ref:`εκτιμώμενα "
```suggestion
"Τα όρια και οι περιορισμοί για μεταβλητές τύπου (:ref:`lazily evaluated "
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"καθυστερημένα <lazy-evaluation>`)."
```suggestion
"<lazy-evaluation>`)."
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"Η τιμή των ψευδωνύμων τύπου (:ref:`εκτιμώμενη καθυστερημένα <lazy-"
```suggestion
"Η τιμή των ψευδωνύμων τύπου (:ref:`lazily evaluated <lazy-"
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"Τα πεδία σημειώσεων διαφέρουν από τα πεδία συναρτήσεων με τους εξής τρόπους:"
```suggestion
"Τα πεδία σημειογραφίας διαφέρουν από τα πεδία συναρτήσεων με τους εξής τρόπους:"
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"Τα πεδία σημειώσεων έχουν πρόσβαση στον χώρο ονομάτων της περιβάλλουσας "
```suggestion
"Τα πεδία σημειογραφίας έχουν πρόσβαση στον χώρο ονομάτων της περιβάλλουσας "
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"κλάσης. Αν ένα πεδίο σημειώσεων βρίσκεται αμέσως μέσα σε έναν χώρο κλάσης ή "
```suggestion
"κλάσης. Αν ένα πεδίο σημειογραφίας βρίσκεται αμέσως μέσα σε έναν χώρο κλάσης ή "
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"μέσα σε ένα άλλο πεδίο σημειώσεων που βρίσκεται αμέσως μέσα σε έναν χώρο "
```suggestion
"μέσα σε ένα άλλο πεδίο σημειογραφίας που βρίσκεται αμέσως μέσα σε έναν χώρο "
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"κλάσης, ο κώδικας στο πεδίο σημειώσεων μπορεί να χρησιμοποιεί ονόματα που "
```suggestion
"κλάσης, ο κώδικας στο πεδίο σημειογραφίας μπορεί να χρησιμοποιεί ονόματα που "
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"Οι εκφράσεις σε πεδία σημειώσεων δεν μπορούν να περιέχουν τις εκφράσεις :"
```suggestion
"Οι εκφράσεις σε πεδία σημειογραφίας δεν μπορούν να περιέχουν τις εκφράσεις :"
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"πεδία που περιέχονται μέσα στο πεδίο σημειώσεων.)"
```suggestion
"πεδία που περιέχονται μέσα στο πεδίο σημειογραφίας.)"
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"Τα ονόματα που ορίζονται σε πεδία σημειώσεων δεν μπορούν να δεσμευτούν εκ "
```suggestion
"Τα ονόματα που ορίζονται σε πεδία σημειογραφίας δεν μπορούν να δεσμευτούν εκ "
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"Ενώ τα πεδία σημειώσεων έχουν ένα εσωτερικό όνομα, αυτό το όνομα δεν "
```suggestion
"Ενώ τα πεδία σημειογραφίας έχουν ένα εσωτερικό όνομα, αυτό το όνομα δεν "
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"αντικειμένων είναι σαν το αντικείμενο να είχε οριστεί στο περιβάλλον πεδίο."
```suggestion
"αντικειμένων είναι σαν το αντικείμενο να είχε οριστεί στο περιβάλλων πεδίο."
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"αμοιβαία αναδρομικών ψευδωνύμων τύπων::"
```suggestion
"αμοιβαίων αναδρομικών ψευδωνύμων τύπων::"
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"σημειώσεων <annotation-scopes>`, που σημαίνει ότι τα ονόματα που "
```suggestion
"σημειογραφίας <annotation-scopes>`, που σημαίνει ότι τα ονόματα που "
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"συνθήκες. Μια εξαίρεση  *εγείρεται* στο σημείο όπου εντοπίζεται το σφάλμα· "
```suggestion
"συνθήκες. Μια εξαίρεση *γίνεται raise* στο σημείο όπου εντοπίζεται το σφάλμα· "
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +"αναφέρεται στην κλάση του στιγμιότυπου  ή σε μια :term:`μη εικονική βασική "
```suggestion
"αναφέρεται στην κλάση του στιγμιότυπου ή σε μια :term:`μη εικονική βασική "
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +msgstr "δέσμευση"
```suggestion
msgstr "σύνδεση"
```

2024-12-10 22:42 UTC, skpanagiotis commented on reference/executionmodel.po
> +msgstr "εγείρει μια εξαίρεση"
```suggestion
msgstr "κάνει raise μια εξαίρεση"
```

2024-12-11 00:21 UTC, mgiannopoulos24 commented
Θα ήταν εύκολο να έχω μερικά παραδείγματα λέξεων που **δεν** χρειάζονται στο `main.txt` προτού κάνω commit την αρχική έκδοση;

2024-12-11 08:31 UTC, skpanagiotis commented
Αυτή τη στιγμή, από ένα γρήγορο πέρασμα που έκανα στο main.txt του PR έχει βάλει στο λεξικό αγγλικές, ελληνικές 
λέξεις χωρίς τόνους ακόμη και τα translator names. To λεξικό πρέπει να περιέχει πρακτικά λέξεις που δεν βρίσκει το pospell στο el_GR.dic.  Κυρίως μερικές αγγλικές που αφήνουμε αμετάφραστες πχ module, token κλπ και ελληνικές λέξεις που δεν υπάρχουν στο el_GR ή λίγο "φτιαχτές λέξεις" π.χ. μεταδεδομένα,

2024-12-11 11:53 UTC, mgiannopoulos24 commented
Εντάξει λοιπόν. Θα ξαναβάλω την αρχική έκδοση .

2024-12-11 12:45 UTC, skpanagiotis commented
Παρόλα αυτά είναι μια καλή ευκαρία να βελτιώσεις το script που έφτιαξες, έχοντας το δικό σου αρχείο που μετέφρασες ως reference (ως ένα δικό σου αληθινό παράδειγμα), ειδικότερα τώρα που έχει μια εικόνα για το τι "έκανε" το script στο λεξικό.

2024-12-12 07:49 UTC, skpanagiotis approved these changes
Μπράβο @mgiannopoulos24 εξαιρετικά!👏

2024-12-12 07:50 UTC, merged