Translate faq/library
pygreece/python-docs-gr pull request #575
Opened 2024-12-10 21:29 UTC by skpanagiotis

## Ποιο issue κλείνει το συγκεκριμένο PR;

Closes #31 

## Περιγραφή του PR

Μετάφραση του αρχείου faq/library.po και προσθήκη κάποιων λέξεω στο λεξικό.

2024-12-16 17:49 UTC, lysnikolaou commented
@skpanagiotis Φαινεται οτι κατι εγινε messed up με τα commits. Μπορεις να κανεις rebase στο main?

2024-12-16 18:27 UTC, skpanagiotis commented
Ωχ όντως δεν το είχα πάρει είδηση, ναι θα το κοιτάξω.

2024-12-16 19:02 UTC, skpanagiotis commented
Μένει να φτιάξω το λεξικό.

2025-02-26 21:59 UTC, gmargaritis requested changes
Awesome work on this one 🎊

Couple of comments!

2025-02-26 21:59 UTC, gmargaritis commented on faq/library.po
> +msgstr "Πως δημιουργώ ένα εκτελέσιμο Python Script στο Unix;"
Any reason that's upper case?

```suggestion
msgstr "Πως δημιουργώ ένα εκτελέσιμο Python script στο Unix;"
```

2025-02-26 21:59 UTC, gmargaritis commented on faq/library.po
> +"Το δεύτερο μπορεί να γίνει με μια σειρά από ποικίλους τρόπους.  Ο πιο απλός "
```suggestion
"Το δεύτερο μπορεί να γίνει με ποικίλους τρόπους.  Ο πιο απλός "
```

2025-02-26 21:59 UTC, gmargaritis commented on faq/library.po
> +"ως η πρώτη γραμμή του αρχείου σας, χρησιμοποιώντας το όνομα διαδρομής για το "
Is pathname something that we regularly translate like this?

```suggestion
"ως η πρώτη γραμμή του αρχείου σας, χρησιμοποιώντας το pathname για το "
```

2025-02-26 21:59 UTC, gmargaritis commented on faq/library.po
> +msgstr "Ακολουθεί ένα ασήμαντο παράδειγμα::"
```suggestion
msgstr "Ένα απλό παράδειγμα::"
```

2025-02-26 21:59 UTC, gmargaritis commented on faq/library.po
> +"mod:`_thread`."
```suggestion
"Βεβαιωθείτε ότι χρησιμοποιείτε το module :mod:`threading` και όχι το module :"
"mod:`_thread`. Το module :mod:`threading` παρέχει ένα πιο βολικό και υψηλού επιπέδου τρόπο διαχείρισης νημάτων, χτίζοντας πάνω στις βασικές λειτουργίες του module :mod:`_thread`."
```

2025-02-26 21:59 UTC, gmargaritis commented on faq/library.po
> +msgstr "Δεν μπορούμε να απαλλαγούμε από την Global Interpreter Lock;"
We used "ένα" to describe the GIL before

```suggestion
msgstr "Μπορούμε να απαλλαγούμε από ένα Global Interpreter Lock;"
```

2025-02-26 21:59 UTC, gmargaritis commented on faq/library.po
> +"Ο :term:`global interpreter lock` (GIL) θεωρείται συχνά ως εμπόδιο για την "
Same here

```suggestion
"Το :term:`global interpreter lock` (GIL) θεωρείται συχνά ως εμπόδιο για την "
```

2025-02-26 21:59 UTC, gmargaritis commented on faq/library.po
> +"μηχανές πολλαπλών CPU! Απλώς πρέπει να είστε δημιουργικοί μοιράζοντας την "
```suggestion
"μηχανήματα πολλαπλών επεξεργαστών Απλώς πρέπει να είστε δημιουργικοί μοιράζοντας την "
```

2025-02-26 21:59 UTC, gmargaritis commented on faq/library.po
> +"func:`open`).  Εάν χρησιμοποιείτε ``\"r\"`` αντί (η προεπιλογή) το αρχείο θα "
```suggestion
"func:`open`).  Εάν χρησιμοποιείσετε το ``\"r\"`` αντί αυτού (προεπιλογμένο) το αρχείο θα "
```

2025-02-26 21:59 UTC, gmargaritis commented on faq/library.po
> +msgstr "Βάσης Δεδομένων"
```suggestion
msgstr "Βάσεις Δεδομένων"
```

2025-02-26 21:59 UTC, gmargaritis commented on faq/library.po
> +msgstr "Πως υλοποιείται μόνιμα αντικείμενα στην Python;"
```suggestion
msgstr "Πως υλοποιείτε persistent αντικείμενα στην Python;"
```

2025-11-02 20:49 UTC, merged