Translate file library/email.errors.po
pygreece/python-docs-gr pull request #576
Opened 2024-12-13 23:04 UTC by mgiannopoulos24

## Ποιο issue κλείνει το συγκεκριμένο PR;

Closes #74 

## Περιγραφή του PR

Προστέθηκε η μετάφραση του `email.errors.po`.

## Λίστα Εργασιών

- [X] Προσθήκη λέξεων στο ευρετήριο `main.txt`.

2024-12-16 08:24 UTC, skpanagiotis requested changes
👏Εξαιρετική δουλειά, πολύ προσεγμένη, έβαλα μόνο μερικά σχολία.

2024-12-16 08:24 UTC, skpanagiotis commented on library/email.errors.po
> +msgstr "Οι εξής κλάσεις εξαίρεσης ορίζονται στο module :mod:`email.errors`:"
```suggestion
msgstr "Οι εξής κλάσεις εξαιρέσεων ορίζονται στο module :mod:`email.errors`:"
```

2024-12-16 08:24 UTC, skpanagiotis commented on library/email.errors.po
> +"Αυτή είναι η βασική κλάση για όλες τις εξαιρέσεις που μπορεί να προκαλέσει "
```suggestion
"Αυτή είναι η βασική κλάση για όλες τις εξαιρέσεις που μπορεί να κάνει raise "
```

2024-12-16 08:24 UTC, skpanagiotis commented on library/email.errors.po
> +"Εμφανίζεται όταν προστεθεί ένα payload σε ένα αντικείμενο :class:`~email."
```suggestion
"Γίνεται raise όταν προστεθεί ένα payload σε ένα αντικείμενο :class:`~email."
```

2024-12-16 08:24 UTC, skpanagiotis commented on library/email.errors.po
> +"εξαίρεση σπάνια εμφανίζεται στην πράξη. Ωστόσο, η εξαίρεση μπορεί επίσης να "
```suggestion
"εξαίρεση, σπάνια εμφανίζεται στην πράξη. Ωστόσο, η εξαίρεση μπορεί επίσης να "
```

2024-12-16 08:24 UTC, skpanagiotis commented on library/email.errors.po
> +"`multipart/alternative` είχε μια παραμορφωμένη επικεφαλίδα, το φωλιασμένο "
```suggestion
"`multipart/alternative` είχε μια παραμορφωμένη επικεφαλίδα, αυτό το ένθετο "
```

2024-12-16 08:24 UTC, skpanagiotis commented on library/email.errors.po
> +"μήνυμα θα είχε ένα ελάττωμα, αλλά τα περιέχοντα μηνύματα δεν θα είχαν."
```suggestion
"αντικείμενο μηνύματος θα είχε ένα ελάττωμα, αλλά τα μηνύματα που περιέχονται  όχι."
```

2024-12-16 08:24 UTC, skpanagiotis commented on library/email.errors.po
> +"παράδειγμα, εάν ένα μήνυμα που είναι φωλιασμένο μέσα σε ένα :mimetype:"
```suggestion
"παράδειγμα, εάν ένα μήνυμα που είναι ένθετο μέσα σε ένα :mimetype:"
```

2024-12-16 08:24 UTC, skpanagiotis commented on library/email.errors.po
> +":class:`CloseBoundaryNotFoundDefect` -- Βρέθηκε όριο εκκίνησης, αλλά δεν "
```suggestion
":class:`CloseBoundaryNotFoundDefect` -- Βρέθηκε ένα όριο εκκίνησης, αλλά δεν "
```

2024-12-16 08:24 UTC, skpanagiotis commented on library/email.errors.po
> +"συμπλήρωμα ήταν άκυρος (1 παραπάνω από πολλαπλάσιο του 4). Το κωδικοποιημένο "
```suggestion
"συμπλήρωμα ήταν άκυρος (1 παραπάνω από ένα πολλαπλάσιο του 4). Το κωδικοποιημένο "
```

2024-12-16 13:26 UTC, skpanagiotis commented
FYI σε κάθε suggestion υπάρχει ένα button Commit Suggestion. Και κάνει μόνο του commit την αλλαγή.

2024-12-16 13:27 UTC, skpanagiotis approved these changes, later dismissed

2024-12-16 13:32 UTC, mgiannopoulos24 commented
Το γνωρίζω απλά για να μην κάνω πολλά commit τα έφτιαξα χειροκίνητα.

2024-12-16 16:58 UTC, lysnikolaou reviewed
Πολύ καλή δουλειά για άλλη μια φορά. Thanks @mgiannopoulos24! Άφησα μερικά review comments.

2024-12-16 16:58 UTC, lysnikolaou commented on library/email.errors.po
> +"κλάση :class:`~email.parser.Parser`. Παράγεται από την :exc:`MessageError`. "
Νομιζω το "παραγεται" ειναι λαθος εδω. Μαλλον καλυτερα να χρησιμοποιησουμε τον συνωνυμο ορο inherits/κληρονομει.

```suggestion
"κλάση :class:`~email.parser.Parser`. Κληρονομεί από την :exc:`MessageError`. "
```

2024-12-16 16:58 UTC, lysnikolaou commented on library/email.errors.po
> +"προκαλέσει αυτό το σφάλμα για ορισμένα σφάλματα αποκωδικοποίησης base64, "
Αφου απο πανω λεμε "κανω raise", ας συνεχισουμε ετσι και για τις υπολοιπες παραγραφους.

```suggestion
"κάνει raise αυτό το σφάλμα για ορισμένα σφάλματα αποκωδικοποίησης base64, "
```

2024-12-16 16:58 UTC, lysnikolaou commented on library/email.errors.po
> +"εξαίρεση, σπάνια εμφανίζεται στην πράξη. Ωστόσο, η εξαίρεση μπορεί επίσης να "
```suggestion
"εξαίρεση σπάνια εμφανίζεται στην πράξη. Ωστόσο, η εξαίρεση μπορεί επίσης να "
```

2024-12-16 16:58 UTC, lysnikolaou commented on library/email.errors.po
> +"ανάλυση μηνυμάτων email. Είναι παράγωγο της :exc:`ValueError`."
```suggestion
"ανάλυση μηνυμάτων email. Είναι παράγωγη της :exc:`ValueError`."
```

2024-12-16 16:58 UTC, lysnikolaou commented on library/email.errors.po
> +"ανάλυση των επικεφαλίδων email. Είναι παράγωγο της :exc:`MessageDefect`."
Νομιζω ιδανικα πρεπει να ειμαστε consistent αναμεσα στο "κεφαλιδες" και "επικεφαλιδες" για την λεξη headers. Ο,τι προτιμας εσυ, απλα ας το κανουμε για ολα τα occurences στο συγκεκριμενο αρχειο με τον ιδιο τροπο.

2024-12-16 16:58 UTC, lysnikolaou commented on library/email.errors.po
> +"Ακολουθεί η λίστα με τα ελαττώματα που μπορεί να εντοπίσει ο :class:`~email."
```suggestion
"Ακολουθεί η λίστα με τα ελαττώματα που μπορεί να εντοπίσει η :class:`~email."
```

2024-12-16 16:58 UTC, lysnikolaou commented on library/email.errors.po
> +"μηνύματος θα είχε ένα ελάττωμα, αλλά τα μηνύματα που περιέχονται όχι."
```suggestion
"μηνύματος θα είχε ένα ελάττωμα, αλλά τα μηνύματα που το περιέχουν όχι."
```

2024-12-16 16:58 UTC, lysnikolaou commented on library/email.errors.po
> +"ανάλυση συνεχίζεται υποθέτοντας ότι η γραμμή αντιπροσωπεύει την πρώτη γραμμή "
```suggestion
"ανάλυση συνεχίζεται στην περίπτωση που η γραμμή αντιπροσωπεύει την πρώτη γραμμή "
```

2024-12-16 16:58 UTC, lysnikolaou commented on library/email.errors.po
> +msgstr "Αυτό το σφάλμα δεν έχει χρησιμοποιηθεί για πολλές εκδόσεις της Python."
```suggestion
msgstr "Αυτό το σφάλμα δεν έχει χρησιμοποιηθεί εδώ και πολλές εκδόσεις της Python."
```

2024-12-16 18:21 UTC, mgiannopoulos24 commented on library/email.errors.po
> +"ανάλυση των επικεφαλίδων email. Είναι παράγωγο της :exc:`MessageDefect`."
Ας κάνουμε ότι εσείς νομίζετε.

2024-12-16 21:18 UTC, mgiannopoulos24 commented on library/email.errors.po
> +"ανάλυση των επικεφαλίδων email. Είναι παράγωγο της :exc:`MessageDefect`."
Βλέπω η λέξη "κεφαλίδα" είναι περισσότερο στο κείμενο, άρα αυτό θα βάλω παντού.

2024-12-20 08:50 UTC, skpanagiotis approved these changes

2024-12-21 08:22 UTC, mgiannopoulos24 commented
Καλημέρα. Είναι δυνατόν αν είναι όλα καλά να γίνει merge, διότι θέλω να ξεκινήσω το #450 .

Ευχαριστώ.

2024-12-22 15:49 UTC, merged